// This file is auto-generated by @hey-api/openapi-ts

export interface ApproveAdminQuickBooksClosedPeriodDateShiftData {
  path: {
    outboxId: string;
  };
  body: {
    approvedPostingDate: string;
    reason: string;
  };
  query?: never;
  url: '/api/v1/admin/quickbooks-sync/{outboxId}/approve-closed-period';
}

export interface ApproveAdminQuickBooksClosedPeriodDateShiftErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ApproveAdminQuickBooksClosedPeriodDateShiftError = ApproveAdminQuickBooksClosedPeriodDateShiftErrors[keyof ApproveAdminQuickBooksClosedPeriodDateShiftErrors];

export interface ApproveAdminQuickBooksClosedPeriodDateShiftResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type ApproveAdminQuickBooksClosedPeriodDateShiftResponse = ApproveAdminQuickBooksClosedPeriodDateShiftResponses[keyof ApproveAdminQuickBooksClosedPeriodDateShiftResponses];
