// This file is auto-generated by @hey-api/openapi-ts

export interface ApproveAdminManualPaymentData {
  path: {
    orderId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/orders/{orderId}/manual-payment/approve';
}

export interface ApproveAdminManualPaymentErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ApproveAdminManualPaymentError = ApproveAdminManualPaymentErrors[keyof ApproveAdminManualPaymentErrors];

export interface ApproveAdminManualPaymentResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      orderId: string;
      proofFileId: string;
      reviewerId: string | null;
      reviewNote: string | null;
      senderAccountNumber: string;
      senderAccountTitle: string;
      status: 'APPROVED' | 'REJECTED' | 'RESUBMISSION_REQUESTED' | 'SUBMITTED';
      reviewedAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type ApproveAdminManualPaymentResponse = ApproveAdminManualPaymentResponses[keyof ApproveAdminManualPaymentResponses];
