// This file is auto-generated by @hey-api/openapi-ts

export interface CancelAdminFinanceAdjustmentData {
  path: {
    adjustmentId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/finance-adjustments/{adjustmentId}/cancel';
}

export interface CancelAdminFinanceAdjustmentErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CancelAdminFinanceAdjustmentError = CancelAdminFinanceAdjustmentErrors[keyof CancelAdminFinanceAdjustmentErrors];

export interface CancelAdminFinanceAdjustmentResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      accountingSnapshotId: string;
      actorId: string | null;
      orderId: string;
      orderItemId: string;
      sellerId: string;
      adjustmentType: 'CANCELLATION' | 'CORRECTION' | 'QUANTITY_CHANGE' | 'REFUND' | 'RETURN';
      attachmentReference: string | null;
      buyerDiscountCogsMinorUnits: number;
      commissionAmountMinorUnits: number;
      currency: string;
      grossItemValueMinorUnits: number;
      note: string | null;
      profitMinorUnits: number;
      reason: string;
      rejectionReason: string | null;
      sellerCouponCogsMinorUnits: number;
      sellerPaidAmountMinorUnits: number;
      sellerPayableMinorUnits: number;
      sellerPayoutFeeMinorUnits: number;
      sourceEventDate: string;
      sourceEventKey: string;
      status: 'CANCELLED' | 'INCOMPLETE' | 'PENDING' | 'POSTED' | 'REJECTED';
      approvedAt: string | null;
      approvedBy: string | null;
      cancelledAt: string | null;
      cancelledBy: string | null;
      rejectedAt: string | null;
      rejectedBy: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type CancelAdminFinanceAdjustmentResponse = CancelAdminFinanceAdjustmentResponses[keyof CancelAdminFinanceAdjustmentResponses];
