// This file is auto-generated by @hey-api/openapi-ts

export interface CancelMyAwaitingPaymentOrderData {
  path: {
    orderId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/checkout/orders/{orderId}/cancel';
}

export interface CancelMyAwaitingPaymentOrderErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CancelMyAwaitingPaymentOrderError = CancelMyAwaitingPaymentOrderErrors[keyof CancelMyAwaitingPaymentOrderErrors];

export interface CancelMyAwaitingPaymentOrderResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      restorableListingIds: Array<string>;
    };
    message: string;
    statusCode: 200;
  };
}

export type CancelMyAwaitingPaymentOrderResponse = CancelMyAwaitingPaymentOrderResponses[keyof CancelMyAwaitingPaymentOrderResponses];
