// This file is auto-generated by @hey-api/openapi-ts

export interface CompleteQuickBooksOAuthCallbackData {
  path?: never;
  body?: never;
  query: {
    realmId?: string;
    code?: string;
    error?: string;
    error_description?: string;
    state: string;
  };
  url: '/api/v1/quickbooks/callback';
}

export interface CompleteQuickBooksOAuthCallbackErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  502: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 502;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CompleteQuickBooksOAuthCallbackError = CompleteQuickBooksOAuthCallbackErrors[keyof CompleteQuickBooksOAuthCallbackErrors];
