// This file is auto-generated by @hey-api/openapi-ts

export interface CreateSellerPayoutData {
  path?: never;
  body: {
    sellerId: string;
    amount: number;
    method: string;
    notes?: string | null;
    periodEnd: string;
    periodStart: string;
    reference: string;
    status?: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING';
    paidAt?: string;
  };
  query?: never;
  url: '/api/v1/admin/payouts';
}

export interface CreateSellerPayoutErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  422: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 422;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateSellerPayoutError = CreateSellerPayoutErrors[keyof CreateSellerPayoutErrors];

export interface CreateSellerPayoutResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      sellerId: string;
      amount: number;
      createdByFullName: string;
      method: string;
      notes: string | null;
      periodEnd: string;
      periodStart: string;
      reference: string;
      sellerFullName: string;
      status: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING';
      paidAt: string;
      createdAt: string;
      createdBy: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateSellerPayoutResponse = CreateSellerPayoutResponses[keyof CreateSellerPayoutResponses];
