// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminFinanceAdjustmentData {
  path?: never;
  body: {
    accountingSnapshotId: string;
    orderId: string;
    orderItemId: string;
    adjustmentType: 'CANCELLATION' | 'CORRECTION' | 'QUANTITY_CHANGE' | 'REFUND' | 'RETURN';
    attachmentReference?: string;
    buyerDiscountCogsMinorUnits: number;
    commissionAmountMinorUnits: number;
    grossItemValueMinorUnits: number;
    idempotencyKey: string;
    note?: string;
    profitMinorUnits: number;
    reason: string;
    sellerCouponCogsMinorUnits: number;
    sellerPaidAmountMinorUnits: number;
    sellerPayableMinorUnits: number;
    sellerPayoutFeeMinorUnits: number;
  };
  query?: never;
  url: '/api/v1/admin/finance-adjustments';
}

export interface CreateAdminFinanceAdjustmentErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminFinanceAdjustmentError = CreateAdminFinanceAdjustmentErrors[keyof CreateAdminFinanceAdjustmentErrors];

export interface CreateAdminFinanceAdjustmentResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      accountingSnapshotId: string;
      actorId: string | null;
      orderId: string;
      orderItemId: string;
      sellerId: string;
      adjustmentType: 'CANCELLATION' | 'CORRECTION' | 'QUANTITY_CHANGE' | 'REFUND' | 'RETURN';
      attachmentReference: string | null;
      buyerDiscountCogsMinorUnits: number;
      commissionAmountMinorUnits: number;
      currency: string;
      grossItemValueMinorUnits: number;
      note: string | null;
      profitMinorUnits: number;
      reason: string;
      rejectionReason: string | null;
      sellerCouponCogsMinorUnits: number;
      sellerPaidAmountMinorUnits: number;
      sellerPayableMinorUnits: number;
      sellerPayoutFeeMinorUnits: number;
      sourceEventDate: string;
      sourceEventKey: string;
      status: 'CANCELLED' | 'INCOMPLETE' | 'PENDING' | 'POSTED' | 'REJECTED';
      approvedAt: string | null;
      approvedBy: string | null;
      cancelledAt: string | null;
      cancelledBy: string | null;
      rejectedAt: string | null;
      rejectedBy: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      accountingSnapshotId: string;
      actorId: string | null;
      orderId: string;
      orderItemId: string;
      sellerId: string;
      adjustmentType: 'CANCELLATION' | 'CORRECTION' | 'QUANTITY_CHANGE' | 'REFUND' | 'RETURN';
      attachmentReference: string | null;
      buyerDiscountCogsMinorUnits: number;
      commissionAmountMinorUnits: number;
      currency: string;
      grossItemValueMinorUnits: number;
      note: string | null;
      profitMinorUnits: number;
      reason: string;
      rejectionReason: string | null;
      sellerCouponCogsMinorUnits: number;
      sellerPaidAmountMinorUnits: number;
      sellerPayableMinorUnits: number;
      sellerPayoutFeeMinorUnits: number;
      sourceEventDate: string;
      sourceEventKey: string;
      status: 'CANCELLED' | 'INCOMPLETE' | 'PENDING' | 'POSTED' | 'REJECTED';
      approvedAt: string | null;
      approvedBy: string | null;
      cancelledAt: string | null;
      cancelledBy: string | null;
      rejectedAt: string | null;
      rejectedBy: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminFinanceAdjustmentResponse = CreateAdminFinanceAdjustmentResponses[keyof CreateAdminFinanceAdjustmentResponses];
