// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminDiscountCodeData {
  path?: never;
  body: {
    active?: boolean;
    code: string;
    discountType: 'FIXED' | 'PERCENTAGE';
    discountValue: number;
    maxUses?: number | null;
    maxUsesPerUser?: number | null;
    minOrderAmount?: number;
    expiresAt?: string | null;
  };
  query?: never;
  url: '/api/v1/admin/settings/discount-codes';
}

export interface CreateAdminDiscountCodeErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminDiscountCodeError = CreateAdminDiscountCodeErrors[keyof CreateAdminDiscountCodeErrors];

export interface CreateAdminDiscountCodeResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      active: boolean;
      code: string;
      currentUses: number;
      discountType: 'FIXED' | 'PERCENTAGE';
      discountValue: number;
      maxUses: number | null;
      maxUsesPerUser: number | null;
      minOrderAmount: number;
      expiresAt: string | null;
      createdAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminDiscountCodeResponse = CreateAdminDiscountCodeResponses[keyof CreateAdminDiscountCodeResponses];
