// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminUserData {
  path?: never;
  body: {
    roleId: string;
    email: string;
    firstName: string;
    lastName: string;
    password: string;
    phone: string;
  };
  query?: never;
  url: '/api/v1/admin/users';
}

export interface CreateAdminUserErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminUserError = CreateAdminUserErrors[keyof CreateAdminUserErrors];

export interface CreateAdminUserResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      roleId: string | null;
      address: string;
      email: string;
      firstName: string;
      image: unknown;
      lastName: string;
      marketingEmailConsent: boolean;
      phone: string;
      roleName: string | null;
      /**
       * User status.
       */
      status: 'ACTIVE' | 'INACTIVE';
      termsVersion: string | null;
      username: string;
      marketingEmailConsentUpdatedAt: string | null;
      termsAcceptedAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminUserResponse = CreateAdminUserResponses[keyof CreateAdminUserResponses];
