// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminPayoutRunData {
  path?: never;
  body: {
    approvedAccountingAdjustments?: {
      [key: string]: {
        adjustmentId: string;
        adjustmentScope: 'COMPLAINT' | 'ORDER_ITEM';
        amountMinorUnits: number;
        bankDetails: {
          bankAccountHolder: string;
          bankAccountNumber: string;
          bankIban: string;
          bankName: string;
          bankSwift: string;
        };
        rule: string;
        sourceDate: string;
        type: 'CANCELLATION' | 'QUANTITY_CHANGE' | 'REFUND' | 'RETURN';
      };
    };
    periodEnd: string;
    periodStart: string;
  };
  query?: never;
  url: '/api/v1/admin/payout-runs';
}

export interface CreateAdminPayoutRunErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  422: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 422;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminPayoutRunError = CreateAdminPayoutRunErrors[keyof CreateAdminPayoutRunErrors];

export interface CreateAdminPayoutRunResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      buyerRefundAmount: number;
      buyerRefundItemCount: number;
      generatedByFullName: string;
      itemCount: number;
      periodEnd: string;
      periodStart: string;
      sellerPayoutAmount: number;
      sellerPayoutItemCount: number;
      totalAmount: number;
      generatedBy: string;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminPayoutRunResponse = CreateAdminPayoutRunResponses[keyof CreateAdminPayoutRunResponses];
