// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminCommissionTierData {
  path?: never;
  body: {
    active?: boolean;
    categories: Array<string>;
    maxPrice?: number | null;
    minPrice?: number;
    name: string;
    rate: number;
    sortOrder?: number;
  };
  query?: never;
  url: '/api/v1/admin/settings/commission-tiers';
}

export interface CreateAdminCommissionTierErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminCommissionTierError = CreateAdminCommissionTierErrors[keyof CreateAdminCommissionTierErrors];

export interface CreateAdminCommissionTierResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      active: boolean;
      categories: Array<string>;
      maxPrice: number | null;
      minPrice: number;
      name: string;
      rate: number;
      sortOrder: number;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminCommissionTierResponse = CreateAdminCommissionTierResponses[keyof CreateAdminCommissionTierResponses];
