// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminListingFeedbackData {
  path: {
    listingId: string;
  };
  body: {
    feedback: string;
  };
  query?: never;
  url: '/api/v1/admin/listings/{listingId}/feedback';
}

export interface CreateAdminListingFeedbackErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminListingFeedbackError = CreateAdminListingFeedbackErrors[keyof CreateAdminListingFeedbackErrors];

export interface CreateAdminListingFeedbackResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      adminId: string;
      listingId: string;
      adminFullName: string | null;
      feedback: string;
      createdAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminListingFeedbackResponse = CreateAdminListingFeedbackResponses[keyof CreateAdminListingFeedbackResponses];
