// This file is auto-generated by @hey-api/openapi-ts

export interface CreateReviewData {
  path?: never;
  body: {
    orderId: string;
    orderItemId: string;
    comment?: string;
    imageUrls?: Array<string>;
    rating: number;
    videoUrl?: string;
  };
  query?: never;
  url: '/api/v1/reviews';
}

export interface CreateReviewErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateReviewError = CreateReviewErrors[keyof CreateReviewErrors];

export interface CreateReviewResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      listingId: string;
      offerId: string | null;
      orderId: string | null;
      reviewedId: string;
      reviewerId: string;
      comment: string;
      imageUrls: Array<string>;
      listingTitle: string;
      rating: number;
      reviewedFullName: string;
      reviewerFullName: string;
      role: 'BUYER' | 'SELLER';
      videoUrl: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateReviewResponse = CreateReviewResponses[keyof CreateReviewResponses];
