// This file is auto-generated by @hey-api/openapi-ts

export interface CreateSupportTicketData {
  path?: never;
  body: {
    content: string;
    subject: string;
  };
  query?: never;
  url: '/api/v1/support-tickets';
}

export interface CreateSupportTicketErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateSupportTicketError = CreateSupportTicketErrors[keyof CreateSupportTicketErrors];

export interface CreateSupportTicketResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      lastMessageSenderId: string | null;
      userId: string;
      lastMessageContent: string | null;
      messageCount: number;
      status: 'CLOSED' | 'IN_PROGRESS' | 'OPEN' | 'RESOLVED';
      subject: string;
      userEmail: string;
      userFullName: string;
      lastMessageAt: string;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateSupportTicketResponse = CreateSupportTicketResponses[keyof CreateSupportTicketResponses];
