// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminTaxSettingData {
  path?: never;
  body: {
    active?: boolean;
    name: string;
    rate: number;
  };
  query?: never;
  url: '/api/v1/admin/settings/tax-settings';
}

export interface CreateAdminTaxSettingErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminTaxSettingError = CreateAdminTaxSettingErrors[keyof CreateAdminTaxSettingErrors];

export interface CreateAdminTaxSettingResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      active: boolean;
      name: string;
      rate: number;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminTaxSettingResponse = CreateAdminTaxSettingResponses[keyof CreateAdminTaxSettingResponses];
