// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminSellerCouponData {
  path?: never;
  body: {
    listingId?: string | null;
    sellerId: string;
    active?: boolean;
    maxEligibleUnits?: number | null;
    minOrderAmount?: number;
    percentage: number;
    scope: 'ITEM_BASED' | 'SELLER_WIDE';
    expiresAt?: string | null;
    startsAt?: string | null;
  };
  query?: never;
  url: '/api/v1/admin/seller-coupons';
}

export interface CreateAdminSellerCouponErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminSellerCouponError = CreateAdminSellerCouponErrors[keyof CreateAdminSellerCouponErrors];

export interface CreateAdminSellerCouponResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      listingId: string | null;
      sellerId: string;
      active: boolean;
      maxEligibleUnits: number | null;
      minOrderAmount: number;
      percentage: number;
      reservedEligibleUnits: number;
      scope: 'ITEM_BASED' | 'SELLER_WIDE';
      usedEligibleUnits: number;
      expiresAt: string | null;
      startsAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminSellerCouponResponse = CreateAdminSellerCouponResponses[keyof CreateAdminSellerCouponResponses];
