// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminHelpTutorialData {
  path?: never;
  body: {
    ctaLabel?: string | null;
    ctaTo?: string | null;
    icon?: string | null;
    published?: boolean;
    sortOrder?: number;
    steps: Array<string>;
    title: string;
  };
  query?: never;
  url: '/api/v1/admin/settings/help-tutorials';
}

export interface CreateAdminHelpTutorialErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminHelpTutorialError = CreateAdminHelpTutorialErrors[keyof CreateAdminHelpTutorialErrors];

export interface CreateAdminHelpTutorialResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      ctaLabel: string | null;
      ctaTo: string | null;
      icon: string | null;
      published: boolean;
      sortOrder: number;
      steps: Array<string>;
      title: string;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminHelpTutorialResponse = CreateAdminHelpTutorialResponses[keyof CreateAdminHelpTutorialResponses];
