// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminQuickBooksAccountMappingVersionData {
  path?: never;
  body: {
    effectiveDate: string;
    mappings: Array<{
      accountId: string;
      category: 'ADJUSTMENTS' | 'BUYER_DISCOUNTS_COGS' | 'COMMISSION_REVENUE' | 'PAYMENT_CLEARING' | 'REFUNDS' | 'SELLER_COUPONS_COGS' | 'SELLER_PAYABLE' | 'SELLER_PAYOUT_FEES_COGS';
      displayName: string;
    }>;
    reason: string;
  };
  query?: never;
  url: '/api/v1/admin/quickbooks-account-mappings';
}

export interface CreateAdminQuickBooksAccountMappingVersionErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminQuickBooksAccountMappingVersionError = CreateAdminQuickBooksAccountMappingVersionErrors[keyof CreateAdminQuickBooksAccountMappingVersionErrors];

export interface CreateAdminQuickBooksAccountMappingVersionResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      actorId: string;
      effectiveDate: string;
      mappings: Array<{
        accountId: string;
        category: 'ADJUSTMENTS' | 'BUYER_DISCOUNTS_COGS' | 'COMMISSION_REVENUE' | 'PAYMENT_CLEARING' | 'REFUNDS' | 'SELLER_COUPONS_COGS' | 'SELLER_PAYABLE' | 'SELLER_PAYOUT_FEES_COGS';
        displayName: string;
      }>;
      reason: string;
      version: number;
      createdAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminQuickBooksAccountMappingVersionResponse = CreateAdminQuickBooksAccountMappingVersionResponses[keyof CreateAdminQuickBooksAccountMappingVersionResponses];
