// This file is auto-generated by @hey-api/openapi-ts

export interface CreateAdminQuickBooksSellerVendorMappingData {
  path?: never;
  body: {
    quickbooksApAccountId: string;
    quickbooksVendorId: string;
    sellerId: string;
    displayName: string;
    effectiveDate: string;
    quickbooksApAccountName: string;
    reason: string;
  };
  query?: never;
  url: '/api/v1/admin/quickbooks-seller-vendor-mappings';
}

export interface CreateAdminQuickBooksSellerVendorMappingErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateAdminQuickBooksSellerVendorMappingError = CreateAdminQuickBooksSellerVendorMappingErrors[keyof CreateAdminQuickBooksSellerVendorMappingErrors];

export interface CreateAdminQuickBooksSellerVendorMappingResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      actorId: string;
      quickbooksApAccountId: string | null;
      quickbooksVendorId: string;
      sellerId: string;
      displayName: string;
      effectiveDate: string;
      quickbooksApAccountName: string | null;
      reason: string;
      sellerEmail: string;
      sellerName: string;
      version: number;
      createdAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateAdminQuickBooksSellerVendorMappingResponse = CreateAdminQuickBooksSellerVendorMappingResponses[keyof CreateAdminQuickBooksSellerVendorMappingResponses];
