// This file is auto-generated by @hey-api/openapi-ts

export interface CreateListingPackageBoostsData {
  path: {
    listingId: string;
  };
  body: {
    packageIds: Array<string>;
    paymentStatus?: 'MOCK' | 'PAID';
  };
  query?: never;
  url: '/api/v1/me/listings/{listingId}/boosts/package';
}

export interface CreateListingPackageBoostsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateListingPackageBoostsError = CreateListingPackageBoostsErrors[keyof CreateListingPackageBoostsErrors];

export interface CreateListingPackageBoostsResponses {
  /**
   * Default Response
   */
  201: {
    data: Array<{
      id: string;
      listingId: string;
      packageId: string | null;
      sellerId: string;
      isActive?: boolean;
      packageName: string | null;
      paymentStatus: 'CANCELLED' | 'MOCK' | 'PAID';
      placement: 'FOR_YOU' | 'SEARCH' | 'TRENDING';
      pricePaid: number;
      endsAt: string;
      startsAt: string;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    statusCode: 201;
  };
}

export type CreateListingPackageBoostsResponse = CreateListingPackageBoostsResponses[keyof CreateListingPackageBoostsResponses];
