// This file is auto-generated by @hey-api/openapi-ts

export interface CreateOrderData {
  path?: never;
  body: {
    proofFileId: string;
    discountCode?: string;
    listingIds: Array<string>;
    quoteRevision: string;
    senderAccountNumber: string;
    senderAccountTitle: string;
    shippingAddress: string;
    shippingCity: string;
    shippingFirstName: string;
    shippingLastName: string;
    shippingPhone: string;
    shippingPostal: string;
  };
  query?: never;
  url: '/api/v1/checkout/orders';
}

export interface CreateOrderErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    requestId?: string;
    code?: string;
    data?: {
      quote: {
        appliedSellerCoupons: Array<{
          id: string;
          sellerId: string;
          allocations: Array<{
            listingId: string;
            /**
             * PKR amount as a number.
             */
            discountAmount: number;
          }>;
          code: string;
          /**
           * PKR amount as a number.
           */
          discountAmount: number;
          discountType: 'FIXED' | 'PERCENTAGE';
          discountValue: number;
          scope: 'ITEM_BASED' | 'SELLER_WIDE';
        }>;
        /**
         * PKR amount as a number.
         */
        commissionAmount: number;
        currency: 'PKR';
        /**
         * PKR amount as a number.
         */
        discountAmount: number;
        items: Array<{
          listingId: string;
          sellerCouponId: string | null;
          sellerId: string;
          /**
           * PKR amount as a number.
           */
          commissionAmount: number;
          commissionRate: number;
          /**
           * PKR amount as a number.
           */
          discountAmount: number;
          /**
           * PKR amount as a number.
           */
          marketplaceDiscountAmount: number;
          /**
           * PKR amount as a number.
           */
          platformFeeAmount: number;
          /**
           * PKR amount as a number.
           */
          price: number;
          /**
           * PKR amount as a number.
           */
          sellerCouponDiscountAmount: number;
          /**
           * PKR amount as a number.
           */
          taxAmount: number;
          title: string;
          /**
           * PKR amount as a number.
           */
          total: number;
        }>;
        /**
         * PKR amount as a number.
         */
        marketplaceDiscountAmount: number;
        marketplaceDiscountCode: string | null;
        /**
         * PKR amount as a number.
         */
        platformFeeAmount: number;
        quoteRevision: string;
        /**
         * PKR amount as a number.
         */
        sellerCouponDiscountAmount: number;
        /**
         * PKR amount as a number.
         */
        subtotal: number;
        /**
         * PKR amount as a number.
         */
        subtotalAfterSellerCoupons: number;
        /**
         * PKR amount as a number.
         */
        taxAmount: number;
        taxRate: number;
        /**
         * PKR amount as a number.
         */
        total: number;
        /**
         * PKR amount as a number.
         */
        totalAfterDiscount: number;
      };
    };
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
    message: string;
    statusCode: 409;
  };
}

export type CreateOrderError = CreateOrderErrors[keyof CreateOrderErrors];

export interface CreateOrderResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      manualPaymentSubmission: {
        id: string;
        orderId: string;
        proofFileId: string;
        status: 'APPROVED' | 'REJECTED' | 'RESUBMISSION_REQUESTED' | 'SUBMITTED';
        createdAt: string;
        updatedAt: string;
      };
      order: {
        id: string;
        buyerId: string;
        buyerFullName: string;
        cancellationReason: string | null;
        /**
         * PKR amount as a number.
         */
        commissionAmount: number;
        currency: 'PKR';
        /**
         * PKR amount as a number.
         */
        discountAmount: number;
        discountCode: string | null;
        items: Array<{
          id: string;
          buyerId: string;
          commissionTierId: string | null;
          listingId: string;
          offerId: string | null;
          orderId: string;
          reservationId: string | null;
          sellerCouponId: string | null;
          sellerId: string;
          brand: string;
          buyerFullName: string;
          category: string;
          description: string;
          /**
           * PKR amount as a number.
           */
          commissionAmount: number;
          commissionRate: number;
          commissionTierName: string | null;
          condition: string;
          currency: 'PKR';
          /**
           * PKR amount as a number.
           */
          discountAmount: number;
          expectedDelivery: string | null;
          imageUrl: string;
          /**
           * PKR amount as a number.
           */
          platformFeeAmount: number;
          /**
           * PKR amount as a number.
           */
          price: number;
          proofImageUrl: string | null;
          quantity: number;
          reservedOfferPrice: number | null;
          sellerCouponCode: string | null;
          /**
           * PKR amount as a number.
           */
          sellerCouponDiscountAmount: number;
          sellerFullName: string;
          shippingMethod: string | null;
          size: string;
          status: 'AWAITING_PAYMENT' | 'CANCELLED' | 'CONFIRMED' | 'DELIVERED' | 'SHIPPED';
          subcategory: string;
          /**
           * PKR amount as a number.
           */
          taxAmount: number;
          title: string;
          /**
           * PKR amount as a number.
           */
          total: number;
          trackingNumber: string | null;
          receivedAt: string | null;
          shippedAt: string | null;
          createdAt: string;
          updatedAt: string;
        }>;
        paymentStatus: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING' | 'UNPAID';
        /**
         * PKR amount as a number.
         */
        platformFeeAmount: number;
        refundStatus: 'REFUND_FAILED' | 'REFUND_REQUIRED' | 'REFUNDED' | 'REFUNDING' | null;
        restorableListingIds?: Array<string>;
        sellerCouponApplications: Array<{
          id: string;
          sellerId: string;
          allocations: Array<{
            listingId: string;
            orderItemId: string;
            /**
             * PKR amount as a number.
             */
            discountAmount: number;
          }>;
          code: string;
          /**
           * PKR amount as a number.
           */
          discountAmount: number;
        }>;
        sellerCouponCode: string | null;
        shippingAddress: string;
        shippingCity: string;
        shippingFirstName: string;
        shippingLastName: string;
        shippingPhone: string;
        shippingPostal: string;
        status: 'AWAITING_PAYMENT' | 'CANCELLED' | 'CONFIRMED' | 'DELIVERED' | 'PARTIALLY_DELIVERED' | 'PARTIALLY_SHIPPED' | 'SHIPPED';
        /**
         * PKR amount as a number.
         */
        subtotal: number;
        /**
         * PKR amount as a number.
         */
        taxAmount: number;
        taxRate: number;
        /**
         * PKR amount as a number.
         */
        total: number;
        cancelledAt: string | null;
        expiresAt: string | null;
        paidAt: string | null;
        createdAt: string;
        updatedAt: string;
      };
    };
    message: string;
    statusCode: 200;
  };
}

export type CreateOrderResponse = CreateOrderResponses[keyof CreateOrderResponses];
