// This file is auto-generated by @hey-api/openapi-ts

export interface CreateReportData {
  path?: never;
  body: {
    conversationId?: string;
    listingId?: string;
    messageId?: string;
    reportedUserId?: string;
    details?: string;
    reason: string;
  };
  query?: never;
  url: '/api/v1/reports';
}

export interface CreateReportErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateReportError = CreateReportErrors[keyof CreateReportErrors];

export interface CreateReportResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      conversationId: string | null;
      listingId: string | null;
      messageId: string | null;
      reportedUserId: string | null;
      reporterId: string;
      adminNotes: string | null;
      details: string | null;
      listingTitle: string | null;
      messageContent: string | null;
      reason: string;
      reportedUserFullName: string | null;
      reporterFullName: string;
      resolverFullName: string | null;
      status: 'DISMISSED' | 'OPEN' | 'RESOLVED';
      resolvedAt: string | null;
      resolvedBy: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateReportResponse = CreateReportResponses[keyof CreateReportResponses];
