// This file is auto-generated by @hey-api/openapi-ts

export interface CreateComplaintData {
  path?: never;
  body: {
    orderId: string;
    orderItemId: string;
    evidenceUrls: Array<string>;
    reason: string;
  };
  query?: never;
  url: '/api/v1/complaints';
}

export interface CreateComplaintErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type CreateComplaintError = CreateComplaintErrors[keyof CreateComplaintErrors];

export interface CreateComplaintResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      buyerId: string;
      listingId: string;
      orderId: string;
      orderItemId: string;
      sellerId: string;
      adminNotes: string | null;
      buyerFullName: string;
      evidenceUrls: Array<string>;
      expectedReturnDate: string | null;
      listingTitle: string;
      reason: string;
      resolverFullName: string | null;
      returnAddress: string | null;
      returnAddressCity: string | null;
      returnAddressPhone: string | null;
      returnAddressPostal: string | null;
      returnAddressRecipient: string | null;
      returnCarrier: string | null;
      returnInstructions: string | null;
      returnProofUrls: Array<string>;
      returnTracking: string | null;
      sellerFullName: string;
      status: 'RAISED' | 'REFUNDED' | 'REJECTED' | 'RETURN_ADDRESS_PROVIDED' | 'RETURN_APPROVED' | 'RETURN_IN_TRANSIT' | 'RETURN_RECEIVED' | 'UNDER_REVIEW';
      resolvedAt: string | null;
      resolvedBy: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type CreateComplaintResponse = CreateComplaintResponses[keyof CreateComplaintResponses];
