// This file is auto-generated by @hey-api/openapi-ts

export interface DeleteMyListingData {
  path: {
    listingId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/me/listings/{listingId}';
}

export interface DeleteMyListingErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type DeleteMyListingError = DeleteMyListingErrors[keyof DeleteMyListingErrors];

export interface DeleteMyListingResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type DeleteMyListingResponse = DeleteMyListingResponses[keyof DeleteMyListingResponses];
