// This file is auto-generated by @hey-api/openapi-ts

export interface DeleteAdminDiscountCodeData {
  path: {
    resourceId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/settings/discount-codes/{resourceId}';
}

export interface DeleteAdminDiscountCodeErrors {
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type DeleteAdminDiscountCodeError = DeleteAdminDiscountCodeErrors[keyof DeleteAdminDiscountCodeErrors];

export interface DeleteAdminDiscountCodeResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type DeleteAdminDiscountCodeResponse = DeleteAdminDiscountCodeResponses[keyof DeleteAdminDiscountCodeResponses];
