// This file is auto-generated by @hey-api/openapi-ts

export interface DeleteAdminCommissionTierData {
  path: {
    resourceId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/settings/commission-tiers/{resourceId}';
}

export interface DeleteAdminCommissionTierErrors {
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type DeleteAdminCommissionTierError = DeleteAdminCommissionTierErrors[keyof DeleteAdminCommissionTierErrors];

export interface DeleteAdminCommissionTierResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type DeleteAdminCommissionTierResponse = DeleteAdminCommissionTierResponses[keyof DeleteAdminCommissionTierResponses];
