// This file is auto-generated by @hey-api/openapi-ts

export interface DeleteAdminBrandData {
  path: {
    brandId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/brands/{brandId}';
}

export interface DeleteAdminBrandErrors {
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type DeleteAdminBrandError = DeleteAdminBrandErrors[keyof DeleteAdminBrandErrors];

export interface DeleteAdminBrandResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type DeleteAdminBrandResponse = DeleteAdminBrandResponses[keyof DeleteAdminBrandResponses];
