// This file is auto-generated by @hey-api/openapi-ts

export interface DismissAdminFlaggedMessageData {
  path: {
    messageId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/messages/{messageId}/dismiss';
}

export interface DismissAdminFlaggedMessageErrors {
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type DismissAdminFlaggedMessageError = DismissAdminFlaggedMessageErrors[keyof DismissAdminFlaggedMessageErrors];

export interface DismissAdminFlaggedMessageResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      conversationId: string;
      senderId: string;
      content: string;
      flagReasons: Array<string>;
      isFlagged: boolean;
      readAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type DismissAdminFlaggedMessageResponse = DismissAdminFlaggedMessageResponses[keyof DismissAdminFlaggedMessageResponses];
