// This file is auto-generated by @hey-api/openapi-ts

export interface ExportAdminFinanceReportData {
  path?: never;
  body?: never;
  query?: {
    orderId?: string;
    sellerId?: string;
    accountingStatus?: 'INCOMPLETE' | 'PENDING' | 'POSTED';
    category?: string;
    paymentStatus?: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING' | 'UNPAID';
    payoutStatus?: 'PAID' | 'RECEIVABLE_OFFSET' | 'UNPAID';
    periodEnd?: string;
    periodStart?: string;
  };
  url: '/api/v1/admin/finance-reports/export';
}

export interface ExportAdminFinanceReportErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ExportAdminFinanceReportError = ExportAdminFinanceReportErrors[keyof ExportAdminFinanceReportErrors];

export interface ExportAdminFinanceReportResponses {
  /**
   * CSV attachment containing matching finance items and a summary row.
   */
  200: string;
}

export type ExportAdminFinanceReportResponse = ExportAdminFinanceReportResponses[keyof ExportAdminFinanceReportResponses];
