// This file is auto-generated by @hey-api/openapi-ts

export interface ForgotUserPasswordData {
  path?: never;
  body: {
    email: string;
  };
  query?: never;
  url: '/api/v1/auth/forgot-password';
}

export interface ForgotUserPasswordErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ForgotUserPasswordError = ForgotUserPasswordErrors[keyof ForgotUserPasswordErrors];

export interface ForgotUserPasswordResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type ForgotUserPasswordResponse = ForgotUserPasswordResponses[keyof ForgotUserPasswordResponses];
