// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminFinanceReportSummaryData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    orderId?: string;
    sellerId?: string;
    accountingStatus?: 'INCOMPLETE' | 'PENDING' | 'POSTED';
    category?: string;
    paymentStatus?: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING' | 'UNPAID';
    payoutStatus?: 'PAID' | 'RECEIVABLE_OFFSET' | 'UNPAID';
    periodEnd?: string;
    periodStart?: string;
    size: number;
  };
  url: '/api/v1/admin/finance-reports/summary';
}

export interface GetAdminFinanceReportSummaryErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminFinanceReportSummaryError = GetAdminFinanceReportSummaryErrors[keyof GetAdminFinanceReportSummaryErrors];

export interface GetAdminFinanceReportSummaryResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      buyerDiscountCogsMinorUnits: number;
      commissionRevenueMinorUnits: number;
      currency: string;
      grossProfitMinorUnits: number;
      incompleteAmountMinorUnits: number;
      orderValueMinorUnits: number;
      outstandingPayoutMinorUnits: number;
      paidPayoutMinorUnits: number;
      pendingAmountMinorUnits: number;
      quickbooks: {
        syncedAmountMinorUnits: number;
        syncedRecordCount: number;
      };
      reconciliationStatus: {
        incompleteRecordCount: number;
        pendingRecordCount: number;
        postedRecordCount: number;
      };
      sellerCouponCogsMinorUnits: number;
      sellerPayableMinorUnits: number;
      sellerPayoutFeeCogsMinorUnits: number;
      totalCogsMinorUnits: number;
    };
    data: Array<{
      id: string;
      orderId: string;
      orderItemId: string;
      quickbooksBatchId: string | null;
      sellerId: string;
      accountingStatus: 'INCOMPLETE' | 'PENDING' | 'POSTED';
      adjustmentDate: string | null;
      buyerDiscountCogsMinorUnits: number;
      category: string;
      commissionAmountMinorUnits: number;
      currency: string;
      grossItemValueMinorUnits: number;
      orderDate: string;
      paymentStatus: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING' | 'UNPAID';
      payoutStatus: 'PAID' | 'RECEIVABLE_OFFSET' | 'UNPAID';
      postingDate: string | null;
      profitMinorUnits: number;
      recordType: 'ADJUSTMENT' | 'SNAPSHOT';
      sellerCouponCogsMinorUnits: number;
      sellerPaidAmountMinorUnits: number;
      sellerPayableMinorUnits: number;
      sellerPayoutFeeMinorUnits: number;
      sourceEventDate: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminFinanceReportSummaryResponse = GetAdminFinanceReportSummaryResponses[keyof GetAdminFinanceReportSummaryResponses];
