// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminQuickBooksSyncEventsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
    status?: 'AWAITING_CORRECTION' | 'FAILED' | 'PENDING' | 'PROCESSING' | 'RETRY' | 'SYNCED';
  };
  url: '/api/v1/admin/quickbooks-sync';
}

export interface GetAdminQuickBooksSyncEventsErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminQuickBooksSyncEventsError = GetAdminQuickBooksSyncEventsErrors[keyof GetAdminQuickBooksSyncEventsErrors];

export interface GetAdminQuickBooksSyncEventsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      accountingEventId: string;
      accountingPostingBatchId: string | null;
      externalTransactionId: string | null;
      approvedPostingDate: string | null;
      attemptCount: number;
      closedPeriodApprovalReason: string | null;
      correctionApprovalReason: string | null;
      correctionApprovedPostingDate: string | null;
      correctionDetails: string | null;
      lastError: string | null;
      originalPostingDate: string | null;
      postingBatchStatus: 'FAILED' | 'PENDING' | 'PROCESSING' | 'RETRY' | 'SYNCED' | null;
      sourceEventDate: string;
      sourceEventKey: string;
      status: 'AWAITING_CORRECTION' | 'FAILED' | 'PENDING' | 'PROCESSING' | 'RETRY' | 'SYNCED';
      closedPeriodApprovedAt: string | null;
      closedPeriodApprovedBy: string | null;
      correctionApprovedAt: string | null;
      correctionApprovedBy: string | null;
      failedAt: string | null;
      lastAttemptAt: string | null;
      nextAttemptAt: string | null;
      syncedAt: string | null;
      createdAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminQuickBooksSyncEventsResponse = GetAdminQuickBooksSyncEventsResponses[keyof GetAdminQuickBooksSyncEventsResponses];
