// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminComplaintsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
    status?: 'RAISED' | 'REFUNDED' | 'REJECTED' | 'RETURN_ADDRESS_PROVIDED' | 'RETURN_APPROVED' | 'RETURN_IN_TRANSIT' | 'RETURN_RECEIVED' | 'UNDER_REVIEW';
  };
  url: '/api/v1/admin/complaints';
}

export interface GetAdminComplaintsErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminComplaintsError = GetAdminComplaintsErrors[keyof GetAdminComplaintsErrors];

export interface GetAdminComplaintsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      buyerId: string;
      listingId: string;
      orderId: string;
      orderItemId: string;
      sellerId: string;
      adminNotes: string | null;
      buyerFullName: string;
      evidenceUrls: Array<string>;
      expectedReturnDate: string | null;
      listingTitle: string;
      reason: string;
      resolverFullName: string | null;
      returnAddress: string | null;
      returnAddressCity: string | null;
      returnAddressPhone: string | null;
      returnAddressPostal: string | null;
      returnAddressRecipient: string | null;
      returnCarrier: string | null;
      returnInstructions: string | null;
      returnProofUrls: Array<string>;
      returnTracking: string | null;
      sellerFullName: string;
      status: 'RAISED' | 'REFUNDED' | 'REJECTED' | 'RETURN_ADDRESS_PROVIDED' | 'RETURN_APPROVED' | 'RETURN_IN_TRANSIT' | 'RETURN_RECEIVED' | 'UNDER_REVIEW';
      resolvedAt: string | null;
      resolvedBy: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminComplaintsResponse = GetAdminComplaintsResponses[keyof GetAdminComplaintsResponses];
