// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminOrderData {
  path: {
    orderId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/orders/{orderId}';
}

export interface GetAdminOrderErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminOrderError = GetAdminOrderErrors[keyof GetAdminOrderErrors];

export interface GetAdminOrderResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      buyerId: string;
      buyerFullName: string;
      cancellationReason: string | null;
      /**
       * PKR amount as a number.
       */
      commissionAmount: number;
      currency: 'PKR';
      /**
       * PKR amount as a number.
       */
      discountAmount: number;
      discountCode: string | null;
      items: Array<{
        id: string;
        buyerId: string;
        commissionTierId: string | null;
        listingId: string;
        offerId: string | null;
        orderId: string;
        reservationId: string | null;
        sellerId: string;
        brand: string;
        buyerFullName: string;
        category: string;
        description: string;
        /**
         * PKR amount as a number.
         */
        commissionAmount: number;
        commissionRate: number;
        commissionTierName: string | null;
        condition: string;
        currency: 'PKR';
        /**
         * PKR amount as a number.
         */
        discountAmount: number;
        expectedDelivery: string | null;
        imageUrl: string;
        /**
         * PKR amount as a number.
         */
        platformFeeAmount: number;
        /**
         * PKR amount as a number.
         */
        price: number;
        proofImageUrl: string | null;
        quantity: number;
        reservedOfferPrice: number | null;
        /**
         * PKR amount as a number.
         */
        sellerCouponDiscountAmount: number;
        sellerFullName: string;
        shippingMethod: string | null;
        size: string;
        status: 'AWAITING_PAYMENT' | 'CANCELLED' | 'CONFIRMED' | 'DELIVERED' | 'SHIPPED';
        subcategory: string;
        /**
         * PKR amount as a number.
         */
        taxAmount: number;
        title: string;
        /**
         * PKR amount as a number.
         */
        total: number;
        trackingNumber: string | null;
        receivedAt: string | null;
        shippedAt: string | null;
        createdAt: string;
        updatedAt: string;
      }>;
      paymentStatus: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING' | 'UNPAID';
      /**
       * PKR amount as a number.
       */
      platformFeeAmount: number;
      refundStatus: 'REFUND_FAILED' | 'REFUND_REQUIRED' | 'REFUNDED' | 'REFUNDING' | null;
      restorableListingIds?: Array<string>;
      sellerCouponCode: string | null;
      shippingAddress: string;
      shippingCity: string;
      shippingFirstName: string;
      shippingLastName: string;
      shippingPhone: string;
      shippingPostal: string;
      status: 'AWAITING_PAYMENT' | 'CANCELLED' | 'CONFIRMED' | 'DELIVERED' | 'PARTIALLY_DELIVERED' | 'PARTIALLY_SHIPPED' | 'SHIPPED';
      /**
       * PKR amount as a number.
       */
      subtotal: number;
      /**
       * PKR amount as a number.
       */
      taxAmount: number;
      taxRate: number;
      /**
       * PKR amount as a number.
       */
      manualPaymentSubmissions: Array<{
        id: string;
        orderId: string;
        proofFileId: string;
        reviewerId: string | null;
        reviewNote: string | null;
        senderAccountNumber: string;
        senderAccountTitle: string;
        status: 'APPROVED' | 'REJECTED' | 'RESUBMISSION_REQUESTED' | 'SUBMITTED';
        reviewedAt: string | null;
        createdAt: string;
        updatedAt: string;
      }>;
      total: number;
      cancelledAt: string | null;
      expiresAt: string | null;
      paidAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetAdminOrderResponse = GetAdminOrderResponses[keyof GetAdminOrderResponses];
