// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminQuickBooksConnectionData {
  path?: never;
  body?: never;
  query: {
    environment: 'PRODUCTION' | 'SANDBOX';
  };
  url: '/api/v1/admin/quickbooks-connection';
}

export interface GetAdminQuickBooksConnectionErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminQuickBooksConnectionError = GetAdminQuickBooksConnectionErrors[keyof GetAdminQuickBooksConnectionErrors];

export interface GetAdminQuickBooksConnectionResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      environment: 'PRODUCTION' | 'SANDBOX';
      status: 'CONNECTED' | 'DISCONNECTED' | 'REAUTH_REQUIRED';
      accessTokenExpiresAt: string | null;
      connectedAt: string | null;
      disconnectedAt: string | null;
      updatedAt: string | null;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetAdminQuickBooksConnectionResponse = GetAdminQuickBooksConnectionResponses[keyof GetAdminQuickBooksConnectionResponses];
