// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminHelpTutorialsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
  };
  url: '/api/v1/admin/settings/help-tutorials';
}

export interface GetAdminHelpTutorialsErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminHelpTutorialsError = GetAdminHelpTutorialsErrors[keyof GetAdminHelpTutorialsErrors];

export interface GetAdminHelpTutorialsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      ctaLabel: string | null;
      ctaTo: string | null;
      icon: string | null;
      published: boolean;
      sortOrder: number;
      steps: Array<string>;
      title: string;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminHelpTutorialsResponse = GetAdminHelpTutorialsResponses[keyof GetAdminHelpTutorialsResponses];
