// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminFinanceReportItemsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    orderId?: string;
    sellerId?: string;
    accountingStatus?: 'INCOMPLETE' | 'PENDING' | 'POSTED';
    category?: string;
    paymentStatus?: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING' | 'UNPAID';
    payoutStatus?: 'PAID' | 'RECEIVABLE_OFFSET' | 'UNPAID';
    periodEnd?: string;
    periodStart?: string;
    size: number;
  };
  url: '/api/v1/admin/finance-reports/items';
}

export interface GetAdminFinanceReportItemsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminFinanceReportItemsError = GetAdminFinanceReportItemsErrors[keyof GetAdminFinanceReportItemsErrors];

export interface GetAdminFinanceReportItemsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      buyerDiscountCogsMinorUnits: number;
      commissionRevenueMinorUnits: number;
      currency: string;
      grossProfitMinorUnits: number;
      incompleteAmountMinorUnits: number;
      orderValueMinorUnits: number;
      outstandingPayoutMinorUnits: number;
      paidPayoutMinorUnits: number;
      pendingAmountMinorUnits: number;
      quickbooks: {
        syncedAmountMinorUnits: number;
        syncedRecordCount: number;
      };
      reconciliationStatus: {
        incompleteRecordCount: number;
        pendingRecordCount: number;
        postedRecordCount: number;
      };
      sellerCouponCogsMinorUnits: number;
      sellerIncentiveBonusCogsMinorUnits: number;
      sellerPayableMinorUnits: number;
      sellerPayoutFeeCogsMinorUnits: number;
      totalCogsMinorUnits: number;
    };
    data: Array<{
      orderId: string;
      orderItemId: string;
      sellerId: string;
      accountingStatus: 'INCOMPLETE' | 'PENDING' | 'POSTED';
      adjustments: Array<{
        id: string;
        accountingSnapshotId: string;
        quickbooksBatchId: string | null;
        quickbooksTransactionId: string | null;
        adjustmentType: 'CANCELLATION' | 'CORRECTION' | 'QUANTITY_CHANGE' | 'REFUND' | 'RETURN';
        buyerDiscountCogsMinorUnits: number;
        commissionAmountMinorUnits: number;
        grossItemValueMinorUnits: number;
        postingDate: string | null;
        profitMinorUnits: number;
        quickbooksSyncStatus: 'UNKNOWN';
        reason: string;
        recordType: 'ADJUSTMENT';
        sellerCouponCogsMinorUnits: number;
        sellerIncentiveBonusCogsMinorUnits: number;
        sellerPayableMinorUnits: number;
        sellerPayoutFeeMinorUnits: number;
        sourceEventDate: string;
        sourceEventKey: string;
        status: 'INCOMPLETE' | 'PENDING' | 'POSTED';
      }>;
      buyerDiscountCogsMinorUnits: number;
      category: string;
      commissionAmountMinorUnits: number;
      commissionBaseMinorUnits: number;
      commissionRateBasisPoints: number;
      currency: string;
      grossItemValueMinorUnits: number;
      itemTitle: string;
      orderDate: string;
      outstandingAmountMinorUnits: number;
      paymentStatus: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING' | 'UNPAID';
      payoutEvents: Array<{
        id: string;
        amountMinorUnits: number | null;
        sourceEventDate: string | null;
        sourceEventKey: string;
        status: 'INCOMPLETE' | 'PAID' | 'REVERSAL';
      }>;
      payoutFeeRule: string;
      payoutStatus: 'PAID' | 'RECEIVABLE_OFFSET' | 'UNPAID';
      postingDate: string | null;
      profitMinorUnits: number;
      sellerCouponCogsMinorUnits: number;
      sellerIncentiveBonusCogsMinorUnits: number;
      sellerPaidAmountMinorUnits: number;
      sellerPayableMinorUnits: number;
      sellerPayoutFeeMinorUnits: number;
      sellerPayoutStatuses: Array<{
        id: string;
        periodEnd: string;
        periodStart: string;
        status: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING';
        paidAt: string;
      }>;
      snapshot: {
        id: string;
        quickbooksBatchId: string | null;
        quickbooksTransactionId: string | null;
        postingDate: string | null;
        quickbooksSyncStatus: 'UNKNOWN';
        reason: string;
        recordType: 'SNAPSHOT';
        sourceEventDate: string;
        sourceEventKey: string;
        status: 'INCOMPLETE' | 'PENDING' | 'POSTED';
      };
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminFinanceReportItemsResponse = GetAdminFinanceReportItemsResponses[keyof GetAdminFinanceReportItemsResponses];
