// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminBrandByIdData {
  path: {
    brandId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/brands/{brandId}';
}

export interface GetAdminBrandByIdErrors {
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminBrandByIdError = GetAdminBrandByIdErrors[keyof GetAdminBrandByIdErrors];

export interface GetAdminBrandByIdResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      active: boolean;
      name: string;
      sortOrder: number;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetAdminBrandByIdResponse = GetAdminBrandByIdResponses[keyof GetAdminBrandByIdResponses];
