// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminPayoutRunItemsData {
  path: {
    runId: string;
  };
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    itemType?: 'BUYER_REFUND' | 'SELLER_PAYOUT';
    size: number;
    status?: 'PAID' | 'UNPAID';
  };
  url: '/api/v1/admin/payout-runs/{runId}/items';
}

export interface GetAdminPayoutRunItemsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminPayoutRunItemsError = GetAdminPayoutRunItemsErrors[keyof GetAdminPayoutRunItemsErrors];

export interface GetAdminPayoutRunItemsResponses {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      buyerId: string | null;
      complaintId: string | null;
      orderId: string | null;
      orderItemId: string | null;
      payoutRunId: string;
      sellerId: string | null;
      userId: string;
      amount: number;
      bankAccountHolder: string | null;
      bankAccountNumber: string | null;
      bankIban: string | null;
      bankName: string | null;
      bankSwift: string | null;
      itemType: 'BUYER_REFUND' | 'SELLER_PAYOUT';
      payoutComponent: 'BASE' | 'SELLER_INCENTIVE_BONUS';
      periodEnd: string;
      periodStart: string;
      sourceDate: string | null;
      sourceMetadata: unknown;
      sourceStatus: string;
      sourceType: string;
      status: 'PAID' | 'UNPAID';
      userFullName: string;
      paidAt: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminPayoutRunItemsResponse = GetAdminPayoutRunItemsResponses[keyof GetAdminPayoutRunItemsResponses];
