// This file is auto-generated by @hey-api/openapi-ts

export interface GetActiveListingBoostsData {
  path?: never;
  body?: never;
  query?: {
    placement?: 'FOR_YOU' | 'SEARCH' | 'TRENDING';
  };
  url: '/api/v1/boosts/active';
}

export interface GetActiveListingBoostsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetActiveListingBoostsError = GetActiveListingBoostsErrors[keyof GetActiveListingBoostsErrors];

export interface GetActiveListingBoostsResponses {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      listingId: string;
      packageId: string | null;
      sellerId: string;
      isActive?: boolean;
      packageName: string | null;
      paymentStatus: 'CANCELLED' | 'MOCK' | 'PAID';
      placement: 'FOR_YOU' | 'SEARCH' | 'TRENDING';
      pricePaid: number;
      endsAt: string;
      startsAt: string;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    statusCode: 200;
  };
}

export type GetActiveListingBoostsResponse = GetActiveListingBoostsResponses[keyof GetActiveListingBoostsResponses];
