// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminCategoryByIdData {
  path: {
    categoryId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/categories/{categoryId}';
}

export interface GetAdminCategoryByIdErrors {
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminCategoryByIdError = GetAdminCategoryByIdErrors[keyof GetAdminCategoryByIdErrors];

export interface GetAdminCategoryByIdResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      icon: string;
      label: string;
      sortOrder: number;
      value: string;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetAdminCategoryByIdResponse = GetAdminCategoryByIdResponses[keyof GetAdminCategoryByIdResponses];
