// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminQuickBooksAccountMappingVersionsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
  };
  url: '/api/v1/admin/quickbooks-account-mappings';
}

export interface GetAdminQuickBooksAccountMappingVersionsErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminQuickBooksAccountMappingVersionsError = GetAdminQuickBooksAccountMappingVersionsErrors[keyof GetAdminQuickBooksAccountMappingVersionsErrors];

export interface GetAdminQuickBooksAccountMappingVersionsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      actorId: string;
      effectiveDate: string;
      mappings: Array<{
        accountId: string;
        category: 'ADJUSTMENTS' | 'BUYER_DISCOUNTS_COGS' | 'COMMISSION_REVENUE' | 'PAYMENT_CLEARING' | 'REFUNDS' | 'SELLER_COUPONS_COGS' | 'SELLER_PAYABLE' | 'SELLER_PAYOUT_FEES_COGS';
        displayName: string;
      }>;
      reason: string;
      version: number;
      createdAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminQuickBooksAccountMappingVersionsResponse = GetAdminQuickBooksAccountMappingVersionsResponses[keyof GetAdminQuickBooksAccountMappingVersionsResponses];
