// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminRolesData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/admin/roles';
}

export interface GetAdminRolesErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminRolesError = GetAdminRolesErrors[keyof GetAdminRolesErrors];

export interface GetAdminRolesResponses {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      name: string;
      permissions: Array<{
        id: string;
        name: string;
        createdAt: string;
        updatedAt: string;
      }>;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    statusCode: 200;
  };
}

export type GetAdminRolesResponse = GetAdminRolesResponses[keyof GetAdminRolesResponses];
