// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminUserByIdData {
  path: {
    userId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/admin/users/{userId}';
}

export interface GetAdminUserByIdErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminUserByIdError = GetAdminUserByIdErrors[keyof GetAdminUserByIdErrors];

export interface GetAdminUserByIdResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      address: string;
      dateOfBirth: string;
      email: string;
      firstName: string;
      image: {
        /**
         * Unique identifier of the uploaded file.
         */
        id: string;
        /**
         * Original filename of the uploaded image.
         */
        filename: string;
        /**
         * MIME type of the uploaded image.
         */
        mimetype: string;
        size: number | string;
        /**
         * Publicly accessible URL of the uploaded image.
         */
        url: string;
      } | null;
      lastName: string;
      marketingEmailConsent: boolean;
      phone: string;
      /**
       * User status.
       */
      status: 'ACTIVE' | 'INACTIVE';
      createdAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetAdminUserByIdResponse = GetAdminUserByIdResponses[keyof GetAdminUserByIdResponses];
