// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminMarketingLeadsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
    /**
     * Search term to filter results (applied to supported fields)
     */
    leadStatus?: 'CUSTOMER' | 'ENGAGED' | 'NEW';
    search?: string;
    /**
     * Inclusive end of the analytics date range.
     */
    endTime?: string;
    /**
     * Inclusive start of the analytics date range.
     */
    startTime?: string;
  };
  url: '/api/v1/admin/analytics/marketing-leads';
}

export interface GetAdminMarketingLeadsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminMarketingLeadsError = GetAdminMarketingLeadsErrors[keyof GetAdminMarketingLeadsErrors];

export interface GetAdminMarketingLeadsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      userId: string;
      leadStatus: 'CUSTOMER' | 'ENGAGED' | 'NEW';
      location: string;
      name: string;
      offerCount: number;
      orderCount: number;
      phone: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminMarketingLeadsResponse = GetAdminMarketingLeadsResponses[keyof GetAdminMarketingLeadsResponses];
