// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminQuickBooksRolloutReadinessData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/admin/quickbooks-rollout';
}

export interface GetAdminQuickBooksRolloutReadinessErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminQuickBooksRolloutReadinessError = GetAdminQuickBooksRolloutReadinessErrors[keyof GetAdminQuickBooksRolloutReadinessErrors];

export interface GetAdminQuickBooksRolloutReadinessResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      alerts: Array<string>;
      configuredEnvironment: 'PRODUCTION' | 'SANDBOX';
      counts: {
        failed: number;
        incompleteAccountingRecords: number;
        pending: number;
        reconciled: number | null;
        reconciliationCountsAvailable: boolean;
        repeatedRetries: number;
        retrying: number;
        stalled: number;
        synced: number;
        unmatched: number | null;
      };
      externalPostingPaused: boolean;
      production: {
        accountMappingsComplete: boolean;
        accountMappingVersion: number | null;
        accountMappingVersionMatches: boolean;
        auditHistoryDeletionDisabled: boolean;
        auditHistoryPreservedPendingApproval: boolean;
        auditRetentionPolicyApproved: boolean;
        blockers: Array<string>;
        clientConfigurationPresent: boolean;
        companyIdentityConfigured: boolean;
        companyIdentityVerified: boolean;
        connectionStatus: 'CONNECTED' | 'DISCONNECTED' | 'REAUTH_REQUIRED';
        connectionTokenValid: boolean;
        ready: boolean;
      };
    };
    message: string;
    statusCode: 200;
  };
}

export type GetAdminQuickBooksRolloutReadinessResponse = GetAdminQuickBooksRolloutReadinessResponses[keyof GetAdminQuickBooksRolloutReadinessResponses];
