// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminQuickBooksReconciliationData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    accountId?: string;
    batchId?: string;
    sellerId?: string;
    dateEnd: string;
    dateStart: string;
    reconciliationStatus?: 'ACCOUNT_MISMATCH' | 'AMOUNT_MISMATCH' | 'DUPLICATE' | 'FAILED_SYNC' | 'LINK_MISMATCH' | 'MATCHED' | 'MISSING_QUICKBOOKS' | 'MISSING_SUNDAY_EVENTS' | 'PENDING_SYNC' | 'POSTING_DATE_MISMATCH' | 'POSTING_SIDE_MISMATCH' | 'UNMATCHED_QUICKBOOKS' | 'UNVERIFIED_MAPPING' | 'UNVERIFIED_SOURCE';
    size: number;
    syncStatus?: 'AWAITING_CORRECTION' | 'FAILED' | 'PENDING' | 'PROCESSING' | 'RETRY' | 'SYNCED';
  };
  url: '/api/v1/admin/quickbooks-reconciliation';
}

export interface GetAdminQuickBooksReconciliationErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  503: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 503;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminQuickBooksReconciliationError = GetAdminQuickBooksReconciliationErrors[keyof GetAdminQuickBooksReconciliationErrors];

export interface GetAdminQuickBooksReconciliationResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      accountId: string | null;
      accountingPostingBatchId: string | null;
      externalTransactionId: string | null;
      accountIds: Array<string>;
      currency: string | null;
      differenceMinorUnits: string | null;
      postingDate: string | null;
      recordType: 'BATCH' | 'PAYOUT_BILL' | 'PAYOUT_PAYMENT' | 'QUICKBOOKS_ONLY';
      sellerIds: Array<string>;
      sourceEventCount: number | null;
      sourceEventKeys: Array<string>;
      sourceReferences: Array<{
        id: string;
        type: string;
      }>;
      status: 'ACCOUNT_MISMATCH' | 'AMOUNT_MISMATCH' | 'DUPLICATE' | 'FAILED_SYNC' | 'LINK_MISMATCH' | 'MATCHED' | 'MISSING_QUICKBOOKS' | 'MISSING_SUNDAY_EVENTS' | 'PENDING_SYNC' | 'POSTING_DATE_MISMATCH' | 'POSTING_SIDE_MISMATCH' | 'UNMATCHED_QUICKBOOKS' | 'UNVERIFIED_MAPPING' | 'UNVERIFIED_SOURCE';
      syncStatus: 'AWAITING_CORRECTION' | 'FAILED' | 'PENDING' | 'PROCESSING' | 'RETRY' | 'SYNCED' | null;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminQuickBooksReconciliationResponse = GetAdminQuickBooksReconciliationResponses[keyof GetAdminQuickBooksReconciliationResponses];
