// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminFlaggedMessagesData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
  };
  url: '/api/v1/admin/messages/flagged';
}

export interface GetAdminFlaggedMessagesErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminFlaggedMessagesError = GetAdminFlaggedMessagesErrors[keyof GetAdminFlaggedMessagesErrors];

export interface GetAdminFlaggedMessagesResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      buyerId: string;
      conversationId: string;
      listingId: string;
      sellerId: string;
      senderId: string;
      buyerFullName: string;
      content: string;
      flagReasons: Array<string>;
      isFlagged: boolean;
      listingTitle: string;
      sellerFullName: string;
      conversationCreatedAt: string;
      readAt: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminFlaggedMessagesResponse = GetAdminFlaggedMessagesResponses[keyof GetAdminFlaggedMessagesResponses];
