// This file is auto-generated by @hey-api/openapi-ts

export interface GetAdminUsersData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
    /**
     * Search term to filter results (applied to supported fields)
     */
    roleType?: 'STAFF' | 'USER';
    search?: string;
    /**
     * User status.
     */
    status?: 'ACTIVE' | 'INACTIVE';
  };
  url: '/api/v1/admin/users';
}

export interface GetAdminUsersErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetAdminUsersError = GetAdminUsersErrors[keyof GetAdminUsersErrors];

export interface GetAdminUsersResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      roleId: string | null;
      address: string;
      email: string;
      firstName: string;
      image: unknown;
      lastName: string;
      marketingEmailConsent: boolean;
      phone: string;
      roleName: string | null;
      /**
       * User status.
       */
      status: 'ACTIVE' | 'INACTIVE';
      termsVersion: string | null;
      username: string;
      marketingEmailConsentUpdatedAt: string | null;
      termsAcceptedAt: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses];
