// This file is auto-generated by @hey-api/openapi-ts

export interface GetBoostPackagesData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/boost-packages';
}

export interface GetBoostPackagesErrors {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetBoostPackagesError = GetBoostPackagesErrors[keyof GetBoostPackagesErrors];

export interface GetBoostPackagesResponses {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      active: boolean;
      credits: number;
      description: string;
      durationDays: number;
      name: string;
      placement: 'FOR_YOU' | 'SEARCH' | 'TRENDING';
      price: number;
    }>;
    message: string;
    statusCode: 200;
  };
}

export type GetBoostPackagesResponse = GetBoostPackagesResponses[keyof GetBoostPackagesResponses];
