// This file is auto-generated by @hey-api/openapi-ts

export interface GetCommissionTiersData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/commission-tiers';
}

export interface GetCommissionTiersErrors {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetCommissionTiersError = GetCommissionTiersErrors[keyof GetCommissionTiersErrors];

export interface GetCommissionTiersResponses {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      active: boolean;
      categories: Array<string>;
      maxPrice: number | null;
      minPrice: number;
      name: string;
      rate: number;
      sortOrder: number;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    statusCode: 200;
  };
}

export type GetCommissionTiersResponse = GetCommissionTiersResponses[keyof GetCommissionTiersResponses];
