// This file is auto-generated by @hey-api/openapi-ts

export interface GetContactInfoData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/contact-info';
}

export interface GetContactInfoErrors {
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetContactInfoError = GetContactInfoErrors[keyof GetContactInfoErrors];

export interface GetContactInfoResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      addressBody: string;
      addressLabel: string;
      emailAddress: string;
      emailLabel: string;
      mapUrl: string;
      officeHours: string;
      phoneLabel: string;
      phoneNumber: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetContactInfoResponse = GetContactInfoResponses[keyof GetContactInfoResponses];
