// This file is auto-generated by @hey-api/openapi-ts

export interface GetHelpCategoriesData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/help-categories';
}

export interface GetHelpCategoriesErrors {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetHelpCategoriesError = GetHelpCategoriesErrors[keyof GetHelpCategoriesErrors];

export interface GetHelpCategoriesResponses {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      key: string;
      active: boolean;
      blurb: string;
      icon: string;
      label: string;
      sortOrder: number;
    }>;
    message: string;
    statusCode: 200;
  };
}

export type GetHelpCategoriesResponse = GetHelpCategoriesResponses[keyof GetHelpCategoriesResponses];
