// This file is auto-generated by @hey-api/openapi-ts

export interface GetHealthData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/health';
}

export interface GetHealthErrors {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export interface GetHealthResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      app: 'ok';
      database: 'ok';
      timestamp: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
