// This file is auto-generated by @hey-api/openapi-ts

export interface GetHelpTutorialsData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/help-tutorials';
}

export interface GetHelpTutorialsErrors {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetHelpTutorialsError = GetHelpTutorialsErrors[keyof GetHelpTutorialsErrors];

export interface GetHelpTutorialsResponses {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      ctaLabel: string | null;
      ctaTo: string | null;
      icon: string | null;
      published: boolean;
      sortOrder: number;
      steps: Array<string>;
      title: string;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    statusCode: 200;
  };
}

export type GetHelpTutorialsResponse = GetHelpTutorialsResponses[keyof GetHelpTutorialsResponses];
