// This file is auto-generated by @hey-api/openapi-ts

export interface GetMyPreferencesData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/preferences/me';
}

export interface GetMyPreferencesErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMyPreferencesError = GetMyPreferencesErrors[keyof GetMyPreferencesErrors];

export interface GetMyPreferencesResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      userId: string;
      brands: Array<string>;
      budgetMax: number | null;
      budgetMin: number | null;
      categories: Array<string>;
      onboardingCompleted: boolean;
      preferredFit: string | null;
      styles: Array<string>;
      whatsappTransactionalNotificationsEnabled: boolean;
      whatsappConsentAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetMyPreferencesResponse = GetMyPreferencesResponses[keyof GetMyPreferencesResponses];
