// This file is auto-generated by @hey-api/openapi-ts

export interface GetMyProfileData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/profiles/me';
}

export interface GetMyProfileErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMyProfileError = GetMyProfileErrors[keyof GetMyProfileErrors];

export interface GetMyProfileResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      userId: string;
      address: string;
      bankAccountHolder: string;
      bankAccountNumber: string;
      bankIban: string;
      bankName: string;
      bankSwift: string;
      bio: string;
      dateOfBirth: string;
      fullName: string;
      image: {
        /**
         * Unique identifier of the uploaded file.
         */
        id: string;
        /**
         * Original filename of the uploaded image.
         */
        filename: string;
        /**
         * MIME type of the uploaded image.
         */
        mimetype: string;
        size: number | string;
        /**
         * Publicly accessible URL of the uploaded image.
         */
        url: string;
      } | null;
      location: string;
      phone: string;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetMyProfileResponse = GetMyProfileResponses[keyof GetMyProfileResponses];
