// This file is auto-generated by @hey-api/openapi-ts

export interface GetMyBoostsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
  };
  url: '/api/v1/me/boosts';
}

export interface GetMyBoostsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMyBoostsError = GetMyBoostsErrors[keyof GetMyBoostsErrors];

export interface GetMyBoostsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      listingId: string;
      packageId: string | null;
      sellerId: string;
      isActive?: boolean;
      packageName: string | null;
      paymentStatus: 'CANCELLED' | 'MOCK' | 'PAID';
      placement: 'FOR_YOU' | 'SEARCH' | 'TRENDING';
      pricePaid: number;
      endsAt: string;
      startsAt: string;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetMyBoostsResponse = GetMyBoostsResponses[keyof GetMyBoostsResponses];
