// This file is auto-generated by @hey-api/openapi-ts

export interface GetMyListingsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
  };
  url: '/api/v1/me/listings';
}

export interface GetMyListingsErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMyListingsError = GetMyListingsErrors[keyof GetMyListingsErrors];

export interface GetMyListingsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      categoryId: string;
      sellerId: string;
      subcategoryId: string;
      brand: string;
      categoryLabel: string;
      categoryValue: string;
      condition: string;
      coverImage: {
        /**
         * Unique identifier of the uploaded file.
         */
        id: string;
        /**
         * Original filename of the uploaded file.
         */
        filename: string;
        /**
         * MIME type of the uploaded file.
         */
        mimetype: string;
        size: number | string;
        /**
         * Publicly accessible URL of the uploaded file.
         */
        url: string;
      };
      description: string;
      media: Array<{
        id: string;
        file: {
          /**
           * Unique identifier of the uploaded file.
           */
          id: string;
          /**
           * Original filename of the uploaded file.
           */
          filename: string;
          /**
           * MIME type of the uploaded file.
           */
          mimetype: string;
          size: number | string;
          /**
           * Publicly accessible URL of the uploaded file.
           */
          url: string;
        };
        sortOrder: number;
        type: 'IMAGE' | 'VIDEO';
        createdAt: string;
      }>;
      /**
       * PKR amount as a number.
       */
      price: number;
      reservedUntil: string | null;
      size: '35' | '36' | '37' | '38' | '39' | '40' | '41' | '42' | '43' | '44' | '45' | '46' | '47' | '48' | 'L' | 'M' | 'One Size' | 'S' | 'XL' | 'XS' | 'XXL' | 'XXS';
      status: 'APPROVED' | 'NEEDS_REVISION' | 'PENDING' | 'REJECTED' | 'RESERVED' | 'SOLD';
      subcategoryLabel: string;
      subcategoryValue: string;
      title: string;
      weight: 0.25 | 0.75 | 1.5 | 2.5 | 4 | 6 | null;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetMyListingsResponse = GetMyListingsResponses[keyof GetMyListingsResponses];
