// This file is auto-generated by @hey-api/openapi-ts

export interface GetMyOfferAmountByIdData {
  path: {
    offerId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/me/offers/{offerId}';
}

export interface GetMyOfferAmountByIdErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMyOfferAmountByIdError = GetMyOfferAmountByIdErrors[keyof GetMyOfferAmountByIdErrors];

export interface GetMyOfferAmountByIdResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      amount: number;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetMyOfferAmountByIdResponse = GetMyOfferAmountByIdResponses[keyof GetMyOfferAmountByIdResponses];
