// This file is auto-generated by @hey-api/openapi-ts

export interface GetMyPayoutsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    periodEnd?: string;
    periodStart?: string;
    size: number;
  };
  url: '/api/v1/me/payouts';
}

export interface GetMyPayoutsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  422: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 422;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMyPayoutsError = GetMyPayoutsErrors[keyof GetMyPayoutsErrors];

export interface GetMyPayoutsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates: {
      eligibleAmount: number;
      paidAmount: number;
      remainingEligibleAmount: number;
    };
    data: Array<{
      id: string;
      sellerId: string;
      amount: number;
      createdByFullName: string;
      method: string;
      notes: string | null;
      periodEnd: string;
      periodStart: string;
      reference: string;
      status: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING';
      paidAt: string;
      createdAt: string;
      createdBy: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetMyPayoutsResponse = GetMyPayoutsResponses[keyof GetMyPayoutsResponses];
