// This file is auto-generated by @hey-api/openapi-ts

export interface GetMarketplaceSellerProfileData {
  path: {
    userId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/users/{userId}';
}

export interface GetMarketplaceSellerProfileErrors {
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMarketplaceSellerProfileError = GetMarketplaceSellerProfileErrors[keyof GetMarketplaceSellerProfileErrors];

export interface GetMarketplaceSellerProfileResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      userId: string;
      avatarUrl: string | null;
      bio: string;
      fullName: string;
      image: {
        /**
         * Unique identifier of the uploaded file.
         */
        id: string;
        /**
         * Original filename of the uploaded image.
         */
        filename: string;
        /**
         * MIME type of the uploaded image.
         */
        mimetype: string;
        size: number | string;
        /**
         * Publicly accessible URL of the uploaded image.
         */
        url: string;
      } | null;
      location: string;
      phone: string;
      createdAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetMarketplaceSellerProfileResponse = GetMarketplaceSellerProfileResponses[keyof GetMarketplaceSellerProfileResponses];
