// This file is auto-generated by @hey-api/openapi-ts

export interface GetMyNotificationsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
    status?: 'READ' | 'UNREAD';
  };
  url: '/api/v1/me/notifications';
}

export interface GetMyNotificationsErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMyNotificationsError = GetMyNotificationsErrors[keyof GetMyNotificationsErrors];

export interface GetMyNotificationsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      entityId: string | null;
      userId: string | null;
      audience: 'ADMIN' | 'USER';
      body: string;
      destination: {
        resourceId?: string;
        focusedChild?: {
          resourceId: string;
          resource: 'manualPaymentSubmission' | 'message' | 'orderItem' | 'review' | 'supportTicketMessage';
        };
        recipient?: 'ADMIN' | 'BUYER' | 'SELLER';
        resource: 'complaint' | 'conversation' | 'listing' | 'offer' | 'order' | 'report' | 'seller' | 'supportTicket';
        section: 'detail' | 'editor' | 'list' | 'listings' | 'management' | 'manual-payment-review' | 'messages' | 'moderation' | 'my-returns' | 'received' | 'returned-to-me' | 'reviews' | 'sent' | 'sold';
      } | null;
      entityType: string | null;
      metadata: {
        [key: string]: unknown;
      };
      title: string;
      type: 'COMPLAINT_RAISED' | 'COMPLAINT_UPDATED' | 'LISTING_APPROVED' | 'LISTING_FEEDBACK_ADDED' | 'LISTING_NEEDS_REVISION' | 'LISTING_REJECTED' | 'LISTING_SUBMITTED' | 'MANUAL_PAYMENT_APPROVED' | 'MANUAL_PAYMENT_CANCELLED' | 'MANUAL_PAYMENT_EXPIRED' | 'MANUAL_PAYMENT_REJECTED' | 'MANUAL_PAYMENT_RESUBMISSION_REQUESTED' | 'MANUAL_PAYMENT_SUBMITTED' | 'MESSAGE_RECEIVED' | 'OFFER_ACCEPTED' | 'OFFER_COUNTERED' | 'OFFER_CREATED' | 'OFFER_EXPIRED' | 'OFFER_REJECTED' | 'OFFER_WITHDRAWN' | 'ORDER_CREATED' | 'ORDER_ITEM_DELIVERED' | 'ORDER_ITEM_SHIPPED' | 'PAYMENT_REFUND_REQUIRED' | 'PAYMENT_REFUNDED' | 'REFUND_ACTIVITY_WARNING' | 'RESERVATION_CANCELLED' | 'RESERVATION_CREATED' | 'RESERVATION_EXPIRED' | 'REVIEW_RECEIVED' | 'SUPPORT_TICKET_CREATED' | 'SUPPORT_TICKET_REPLIED' | 'SUPPORT_TICKET_STATUS_UPDATED';
      readAt: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetMyNotificationsResponse = GetMyNotificationsResponses[keyof GetMyNotificationsResponses];
