// This file is auto-generated by @hey-api/openapi-ts

export interface GetMyOrdersData {
  path?: never;
  body?: never;
  query?: {
    page?: number;
    size?: number;
    sortOrder?: 'asc' | 'desc';
    status?: 'AWAITING_PAYMENT' | 'CANCELLED' | 'CONFIRMED' | 'DELIVERED' | 'PARTIALLY_DELIVERED' | 'PARTIALLY_SHIPPED' | 'SHIPPED';
    sortBy?: 'createdAt' | 'updatedAt';
  };
  url: '/api/v1/me/orders';
}

export interface GetMyOrdersErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMyOrdersError = GetMyOrdersErrors[keyof GetMyOrdersErrors];

export interface GetMyOrdersResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      buyerId: string;
      buyerFullName: string;
      cancellationReason: string | null;
      /**
       * PKR amount as a number.
       */
      commissionAmount: number;
      currency: 'PKR';
      /**
       * PKR amount as a number.
       */
      discountAmount: number;
      discountCode: string | null;
      items: Array<{
        id: string;
        buyerId: string;
        commissionTierId: string | null;
        listingId: string;
        offerId: string | null;
        orderId: string;
        reservationId: string | null;
        sellerId: string;
        sellerIncentiveId: string | null;
        brand: string;
        buyerFullName: string;
        category: string;
        description: string;
        /**
         * PKR amount as a number.
         */
        commissionAmount: number;
        commissionRate: number;
        commissionTierName: string | null;
        condition: string;
        currency: 'PKR';
        /**
         * PKR amount as a number.
         */
        discountAmount: number;
        expectedDelivery: string | null;
        imageUrl: string;
        /**
         * PKR amount as a number.
         */
        platformFeeAmount: number;
        /**
         * PKR amount as a number.
         */
        price: number;
        proofImageUrl: string | null;
        quantity: number;
        reservedOfferPrice: number | null;
        sellerFullName: string;
        /**
         * PKR amount as a number.
         */
        sellerIncentiveBonus: number;
        sellerIncentivePercentage: number | null;
        shippingMethod: string | null;
        size: string;
        status: 'AWAITING_PAYMENT' | 'CANCELLED' | 'CONFIRMED' | 'DELIVERED' | 'SHIPPED';
        subcategory: string;
        /**
         * PKR amount as a number.
         */
        taxAmount: number;
        title: string;
        /**
         * PKR amount as a number.
         */
        total: number;
        trackingNumber: string | null;
        receivedAt: string | null;
        shippedAt: string | null;
        createdAt: string;
        updatedAt: string;
      }>;
      paymentStatus: 'CANCELLED' | 'FAILED' | 'PAID' | 'PENDING' | 'UNPAID';
      /**
       * PKR amount as a number.
       */
      platformFeeAmount: number;
      refundStatus: 'REFUND_FAILED' | 'REFUND_REQUIRED' | 'REFUNDED' | 'REFUNDING' | null;
      restorableListingIds?: Array<string>;
      sellerIncentives: Array<{
        id: string;
        sellerId: string;
        allocations: Array<{
          listingId: string;
          orderItemId: string;
          /**
           * PKR amount as a number.
           */
          bonusAmount: number;
        }>;
        /**
         * PKR amount as a number.
         */
        bonusAmount: number;
        percentage: number;
      }>;
      shippingAddress: string;
      shippingCity: string;
      shippingFirstName: string;
      shippingLastName: string;
      shippingPhone: string;
      shippingPostal: string;
      status: 'AWAITING_PAYMENT' | 'CANCELLED' | 'CONFIRMED' | 'DELIVERED' | 'PARTIALLY_DELIVERED' | 'PARTIALLY_SHIPPED' | 'SHIPPED';
      /**
       * PKR amount as a number.
       */
      subtotal: number;
      /**
       * PKR amount as a number.
       */
      taxAmount: number;
      taxRate: number;
      /**
       * PKR amount as a number.
       */
      canCancel: boolean;
      canResubmit: boolean;
      manualPaymentSubmission?: {
        id: string;
        orderId: string;
        proofFileId: string;
        reviewNote: string | null;
        status: 'APPROVED' | 'REJECTED' | 'RESUBMISSION_REQUESTED' | 'SUBMITTED';
        reviewedAt: string | null;
        createdAt: string;
        updatedAt: string;
      };
      total: number;
      cancelledAt: string | null;
      expiresAt: string | null;
      paidAt: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetMyOrdersResponse = GetMyOrdersResponses[keyof GetMyOrdersResponses];
