// This file is auto-generated by @hey-api/openapi-ts

export interface GetMySalesData {
  path?: never;
  body?: never;
  query?: {
    page?: number;
    size?: number;
    sortOrder?: 'asc' | 'desc';
    status?: 'AWAITING_PAYMENT' | 'CANCELLED' | 'CONFIRMED' | 'DELIVERED' | 'SHIPPED';
    sortBy?: 'createdAt' | 'updatedAt';
  };
  url: '/api/v1/me/sales';
}

export interface GetMySalesErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetMySalesError = GetMySalesErrors[keyof GetMySalesErrors];

export interface GetMySalesResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      buyerId: string;
      commissionTierId: string | null;
      listingId: string;
      offerId: string | null;
      orderId: string;
      reservationId: string | null;
      sellerCouponId: string | null;
      sellerId: string;
      brand: string;
      buyerFullName: string;
      category: string;
      description: string;
      /**
       * PKR amount as a number.
       */
      commissionAmount: number;
      commissionRate: number;
      commissionTierName: string | null;
      condition: string;
      currency: 'PKR';
      /**
       * PKR amount as a number.
       */
      discountAmount: number;
      expectedDelivery: string | null;
      imageUrl: string;
      /**
       * PKR amount as a number.
       */
      platformFeeAmount: number;
      /**
       * PKR amount as a number.
       */
      price: number;
      proofImageUrl: string | null;
      quantity: number;
      reservedOfferPrice: number | null;
      sellerCouponCode: string | null;
      /**
       * PKR amount as a number.
       */
      sellerCouponDiscountAmount: number;
      sellerFullName: string;
      shippingMethod: string | null;
      size: string;
      status: 'AWAITING_PAYMENT' | 'CANCELLED' | 'CONFIRMED' | 'DELIVERED' | 'SHIPPED';
      subcategory: string;
      /**
       * PKR amount as a number.
       */
      taxAmount: number;
      title: string;
      /**
       * PKR amount as a number.
       */
      total: number;
      trackingNumber: string | null;
      receivedAt: string | null;
      shippedAt: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetMySalesResponse = GetMySalesResponses[keyof GetMySalesResponses];
