// This file is auto-generated by @hey-api/openapi-ts

export interface GetPublicListingByIdData {
  path: {
    listingId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/listings/{listingId}';
}

export interface GetPublicListingByIdErrors {
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetPublicListingByIdError = GetPublicListingByIdErrors[keyof GetPublicListingByIdErrors];

export interface GetPublicListingByIdResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      categoryId: string;
      sellerId: string;
      subcategoryId: string;
      brand: string;
      categoryLabel: string;
      categoryValue: string;
      condition: string;
      coverImage: {
        /**
         * Unique identifier of the uploaded file.
         */
        id: string;
        /**
         * Original filename of the uploaded file.
         */
        filename: string;
        /**
         * MIME type of the uploaded file.
         */
        mimetype: string;
        size: number | string;
        /**
         * Publicly accessible URL of the uploaded file.
         */
        url: string;
      };
      description: string;
      /**
       * PKR amount as a number.
       */
      coverImageUrl: string | null;
      images: Array<{
        sortOrder: number;
        storageKey: string | null;
        url: string;
      }>;
      imageUrls: Array<string>;
      media: Array<{
        id: string;
        sortOrder: number;
        storageKey: string | null;
        type: 'IMAGE' | 'VIDEO';
        url: string;
        createdAt: string;
      }>;
      price: number;
      reservedUntil: string | null;
      seller: {
        id: string;
        fullName: string;
        image: {
          /**
           * Unique identifier of the uploaded file.
           */
          id: string;
          /**
           * Original filename of the uploaded file.
           */
          filename: string;
          /**
           * MIME type of the uploaded file.
           */
          mimetype: string;
          size: number | string;
          /**
           * Publicly accessible URL of the uploaded file.
           */
          url: string;
        } | null;
        location: string;
      };
      sellerCouponEstimate?: {
        /**
         * PKR amount as a number.
         */
        discountAmount: number;
        /**
         * PKR amount as a number.
         */
        estimatedPrice: number;
        isEstimate: true;
      };
      size: '35' | '36' | '37' | '38' | '39' | '40' | '41' | '42' | '43' | '44' | '45' | '46' | '47' | '48' | 'L' | 'M' | 'One Size' | 'S' | 'XL' | 'XS' | 'XXL' | 'XXS';
      status: 'APPROVED' | 'NEEDS_REVISION' | 'PENDING' | 'REJECTED' | 'RESERVED' | 'SOLD';
      subcategoryLabel: string;
      subcategoryValue: string;
      title: string;
      weight: 0.25 | 0.75 | 1.5 | 2.5 | 4 | 6 | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetPublicListingByIdResponse = GetPublicListingByIdResponses[keyof GetPublicListingByIdResponses];
