// This file is auto-generated by @hey-api/openapi-ts

export interface GetPaymentProofFileData {
  path: {
    fileId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/payment-proof-files/{fileId}';
}

export interface GetPaymentProofFileErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetPaymentProofFileError = GetPaymentProofFileErrors[keyof GetPaymentProofFileErrors];

export interface GetPaymentProofFileResponses {
  /**
   * Payment proof image.
   */
  200: Blob | File;
}

export type GetPaymentProofFileResponse = GetPaymentProofFileResponses[keyof GetPaymentProofFileResponses];
