// This file is auto-generated by @hey-api/openapi-ts

export interface GetReceivedOffersData {
  path?: never;
  body?: never;
  query: {
    /**
     * Page number (starts from 1)
     */
    page: number;
    /**
     * Number of records per page
     */
    size: number;
  };
  url: '/api/v1/me/offers/received';
}

export interface GetReceivedOffersErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetReceivedOffersError = GetReceivedOffersErrors[keyof GetReceivedOffersErrors];

export interface GetReceivedOffersResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      buyerId: string;
      conversationId: string | null;
      listingId: string;
      sellerId: string;
      amount: number;
      buyerFullName: string;
      counterAmount: number | null;
      coverImage: {
        /**
         * Unique identifier of the uploaded file.
         */
        id: string;
        /**
         * Original filename of the uploaded file.
         */
        filename: string;
        /**
         * MIME type of the uploaded file.
         */
        mimetype: string;
        size: number | string;
        /**
         * Publicly accessible URL of the uploaded file.
         */
        url: string;
      } | null;
      listingPrice: number;
      listingStatus: 'APPROVED' | 'NEEDS_REVISION' | 'PENDING' | 'REJECTED' | 'RESERVED' | 'SOLD';
      listingTitle: string;
      message: string | null;
      reservedUntil: string | null;
      sellerFullName: string;
      status: 'ACCEPTED' | 'COUNTERED' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'WITHDRAWN';
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetReceivedOffersResponse = GetReceivedOffersResponses[keyof GetReceivedOffersResponses];
