// This file is auto-generated by @hey-api/openapi-ts

export interface GetReviewStatsData {
  path?: never;
  body?: never;
  query: {
    /**
     * Comma-separated user UUIDs to fetch stats for
     */
    reviewedIds: string;
  };
  url: '/api/v1/reviews/stats';
}

export interface GetReviewStatsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetReviewStatsError = GetReviewStatsErrors[keyof GetReviewStatsErrors];

export interface GetReviewStatsResponses {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      reviewedId: string;
      avgRating: number;
      totalReviews: number;
    }>;
    message: string;
    statusCode: 200;
  };
}

export type GetReviewStatsResponse = GetReviewStatsResponses[keyof GetReviewStatsResponses];
