// This file is auto-generated by @hey-api/openapi-ts

export interface GetReviewsData {
  path?: never;
  body?: never;
  query: {
    listingId?: string;
    reviewedId?: string;
    page: number;
    size: number;
  };
  url: '/api/v1/reviews';
}

export interface GetReviewsErrors {
  /**
   * Bad Request
   */
  400: unknown;
}

export interface GetReviewsResponses {
  /**
   * Default Response
   */
  200: {
    aggregates?: {
      [key: string]: unknown;
    };
    data: Array<{
      id: string;
      listingId: string;
      offerId: string | null;
      orderId: string | null;
      reviewedId: string;
      reviewerId: string;
      comment: string;
      imageUrls: Array<string>;
      listingTitle: string;
      rating: number;
      reviewedFullName: string;
      reviewerFullName: string;
      role: 'BUYER' | 'SELLER';
      videoUrl: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    message: string;
    pagination: {
      /**
       * Current page number
       */
      currentPage: number;
      /**
       * Total number of pages (last available page)
       */
      lastPage: number;
      /**
       * Next page number if available, otherwise null
       */
      nextPage: number | null;
      /**
       * Number of records per page
       */
      perPage: number;
      /**
       * Previous page number if available, otherwise null
       */
      prevPage: number | null;
      /**
       * Total number of records
       */
      total: number;
    };
    statusCode: 200;
  };
}

export type GetReviewsResponse = GetReviewsResponses[keyof GetReviewsResponses];
