// This file is auto-generated by @hey-api/openapi-ts

export interface GetSellerAnalyticsData {
  path?: never;
  body?: never;
  query?: {
    /**
     * Inclusive end of the analytics date range.
     */
    endTime?: string;
    /**
     * Inclusive start of the analytics date range.
     */
    startTime?: string;
  };
  url: '/api/v1/me/seller-analytics';
}

export interface GetSellerAnalyticsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetSellerAnalyticsError = GetSellerAnalyticsErrors[keyof GetSellerAnalyticsErrors];

export interface GetSellerAnalyticsResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      acceptedOffers: number;
      activeListings: number;
      averageRating: number;
      conversionRate: number;
      currency: 'PKR';
      listingCategoryDistribution: Array<{
        category: string;
        count: number;
      }>;
      monthlyAcceptedOfferValue: Array<{
        label: string;
        month: string;
        totalValue: number;
      }>;
      offerStatusCounts: Array<{
        count: number;
        status: 'ACCEPTED' | 'COUNTERED' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'WITHDRAWN';
      }>;
      pendingOffers: number;
      rejectedOffers: number;
      reviewCount: number;
      totalAcceptedOfferValue: number;
      totalOffers: number;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetSellerAnalyticsResponse = GetSellerAnalyticsResponses[keyof GetSellerAnalyticsResponses];
