// This file is auto-generated by @hey-api/openapi-ts

export interface GetSiteSettingByKeyData {
  path: {
    key: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/site-settings/{key}';
}

export interface GetSiteSettingByKeyErrors {
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetSiteSettingByKeyError = GetSiteSettingByKeyErrors[keyof GetSiteSettingByKeyErrors];

export interface GetSiteSettingByKeyResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      key: string;
      value: {
        addressBody: string;
        addressLabel: string;
        emailAddress: string;
        emailLabel: string;
        mapUrl: string;
        officeHours: string;
        phoneLabel: string;
        phoneNumber: string;
      } | {
        alt: string;
        badgeIconUrl: string;
        badgeText: string;
        headlineLine1: string;
        headlineLine1Color: string;
        headlineLine2: string;
        headlineLine2Color: string;
        mobileUrl: string;
        primaryCtaBg: string;
        primaryCtaLabel: string;
        primaryCtaTextColor: string;
        secondaryCtaBorderColor: string;
        secondaryCtaLabel: string;
        secondaryCtaTextColor: string;
        siteLogoUrl: string;
        subtitle: string;
        subtitleColor: string;
        url: string;
      } | {
        ctaLabel: string;
        ctaUrl: string;
        eyebrow: string;
        subtitle: string;
        title: string;
      };
    };
    message: string;
    statusCode: 200;
  };
}

export type GetSiteSettingByKeyResponse = GetSiteSettingByKeyResponses[keyof GetSiteSettingByKeyResponses];
