// This file is auto-generated by @hey-api/openapi-ts

export interface GetTaxSettingsData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/tax-settings';
}

export interface GetTaxSettingsErrors {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetTaxSettingsError = GetTaxSettingsErrors[keyof GetTaxSettingsErrors];

export interface GetTaxSettingsResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      active: boolean;
      name: string;
      rate: number;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type GetTaxSettingsResponse = GetTaxSettingsResponses[keyof GetTaxSettingsResponses];
