// This file is auto-generated by @hey-api/openapi-ts

export interface GetTopHelpFaqsData {
  path?: never;
  body?: never;
  query?: never;
  url: '/api/v1/help-faqs/top';
}

export interface GetTopHelpFaqsErrors {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type GetTopHelpFaqsError = GetTopHelpFaqsErrors[keyof GetTopHelpFaqsErrors];

export interface GetTopHelpFaqsResponses {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string;
      answer: string;
      categoryKey: string;
      published: boolean;
      question: string;
      sortOrder: number;
    }>;
    message: string;
    statusCode: 200;
  };
}

export type GetTopHelpFaqsResponse = GetTopHelpFaqsResponses[keyof GetTopHelpFaqsResponses];
