// This file is auto-generated by @hey-api/openapi-ts

export interface LoginUserData {
  path?: never;
  body: {
    email: string;
    password: string;
  };
  query?: never;
  url: '/api/v1/auth/login';
}

export interface LoginUserErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export interface LoginUserResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      accessToken: string;
      preferences: {
        id: string;
        userId: string;
        brands: Array<string>;
        budgetMax: number | null;
        budgetMin: number | null;
        categories: Array<string>;
        onboardingCompleted: boolean;
        preferredFit: string | null;
        styles: Array<string>;
        whatsappTransactionalNotificationsEnabled: boolean;
        whatsappConsentAt: string | null;
        createdAt: string;
        updatedAt: string;
      };
      profile: {
        id: string;
        userId: string;
        address: string;
        bankAccountHolder: string;
        bankAccountNumber: string;
        bankIban: string;
        bankName: string;
        bankSwift: string;
        bio: string;
        dateOfBirth: string;
        fullName: string;
        image: {
          /**
           * Unique identifier of the uploaded file.
           */
          id: string;
          /**
           * Original filename of the uploaded image.
           */
          filename: string;
          /**
           * MIME type of the uploaded image.
           */
          mimetype: string;
          size: number | string;
          /**
           * Publicly accessible URL of the uploaded image.
           */
          url: string;
        } | null;
        location: string;
        phone: string;
        createdAt: string;
        updatedAt: string;
      };
      refreshToken: string;
      user: {
        id: string;
        roleId: string | null;
        /**
         * Address of the user.
         */
        address: string;
        /**
         * Email address.
         */
        email: string;
        /**
         * First name of the user.
         */
        firstName: string;
        image: {
          /**
           * Unique identifier of the uploaded file.
           */
          id: string;
          /**
           * Original filename of the uploaded image.
           */
          filename: string;
          /**
           * MIME type of the uploaded image.
           */
          mimetype: string;
          size: number | string;
          /**
           * Publicly accessible URL of the uploaded image.
           */
          url: string;
        } | null;
        /**
         * Last name of the user.
         */
        lastName: string;
        marketingEmailConsent: boolean;
        permissions: Array<{
          id: string;
          name: 'ANALYTICS_CREATE' | 'ANALYTICS_DELETE' | 'ANALYTICS_READ' | 'ANALYTICS_UPDATE' | 'BOOSTS_CREATE' | 'BOOSTS_DELETE' | 'BOOSTS_READ' | 'BOOSTS_UPDATE' | 'BRANDS_CREATE' | 'BRANDS_DELETE' | 'BRANDS_READ' | 'BRANDS_UPDATE' | 'CATALOG_CREATE' | 'CATALOG_DELETE' | 'CATALOG_READ' | 'CATALOG_UPDATE' | 'COMPLAINTS_CREATE' | 'COMPLAINTS_DELETE' | 'COMPLAINTS_READ' | 'COMPLAINTS_UPDATE' | 'FINANCE_ADJUSTMENTS_CREATE' | 'FINANCE_ADJUSTMENTS_READ' | 'FINANCE_ADJUSTMENTS_REVIEW' | 'FINANCE_DASHBOARD_CREATE' | 'FINANCE_DASHBOARD_DELETE' | 'FINANCE_DASHBOARD_READ' | 'FINANCE_DASHBOARD_UPDATE' | 'FINANCE_QUICKBOOKS_CONNECTION_MANAGE' | 'FINANCE_QUICKBOOKS_CONNECTION_READ' | 'FINANCE_QUICKBOOKS_MAPPINGS_MANAGE' | 'FINANCE_QUICKBOOKS_MAPPINGS_READ' | 'FINANCE_QUICKBOOKS_SYNC_MANAGE' | 'FINANCE_QUICKBOOKS_SYNC_READ' | 'FINANCE_REPORTS_CREATE' | 'FINANCE_REPORTS_DELETE' | 'FINANCE_REPORTS_READ' | 'FINANCE_REPORTS_UPDATE' | 'LISTINGS_CREATE' | 'LISTINGS_DELETE' | 'LISTINGS_READ' | 'LISTINGS_UPDATE' | 'MARKETING_LEADS_CREATE' | 'MARKETING_LEADS_DELETE' | 'MARKETING_LEADS_READ' | 'MARKETING_LEADS_UPDATE' | 'MESSAGES_CREATE' | 'MESSAGES_DELETE' | 'MESSAGES_READ' | 'MESSAGES_UPDATE' | 'ORDERS_CREATE' | 'ORDERS_DELETE' | 'ORDERS_READ' | 'ORDERS_UPDATE' | 'PAYOUTS_CREATE' | 'PAYOUTS_DELETE' | 'PAYOUTS_READ' | 'PAYOUTS_UPDATE' | 'REPORTS_CREATE' | 'REPORTS_DELETE' | 'REPORTS_READ' | 'REPORTS_UPDATE' | 'RETURNS_CREATE' | 'RETURNS_DELETE' | 'RETURNS_READ' | 'RETURNS_UPDATE' | 'ROLES_AND_PERMISSIONS_CREATE' | 'ROLES_AND_PERMISSIONS_DELETE' | 'ROLES_AND_PERMISSIONS_READ' | 'ROLES_AND_PERMISSIONS_UPDATE' | 'SELLER_COUPONS_CREATE' | 'SELLER_COUPONS_DELETE' | 'SELLER_COUPONS_READ' | 'SELLER_COUPONS_UPDATE' | 'SETTINGS_CREATE' | 'SETTINGS_DELETE' | 'SETTINGS_READ' | 'SETTINGS_UPDATE' | 'SUPPORT_TICKETS_CREATE' | 'SUPPORT_TICKETS_DELETE' | 'SUPPORT_TICKETS_READ' | 'SUPPORT_TICKETS_UPDATE' | 'USERS_CREATE' | 'USERS_DELETE' | 'USERS_READ' | 'USERS_UPDATE';
        }>;
        /**
         * Phone number.
         */
        phone: string;
        roleName: string | null;
        /**
         * User status.
         */
        status: 'ACTIVE' | 'INACTIVE';
        termsVersion: string | null;
        marketingEmailConsentUpdatedAt: string | null;
        termsAcceptedAt: string | null;
      };
    };
    message: string;
    statusCode: 200;
  };
}

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];
