// This file is auto-generated by @hey-api/openapi-ts

export interface ProcessUnsubscribeTokenData {
  path?: never;
  body: {
    token: string;
  };
  query?: never;
  url: '/api/v1/emails/unsubscribe';
}

export interface ProcessUnsubscribeTokenErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ProcessUnsubscribeTokenError = ProcessUnsubscribeTokenErrors[keyof ProcessUnsubscribeTokenErrors];

export interface ProcessUnsubscribeTokenResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type ProcessUnsubscribeTokenResponse = ProcessUnsubscribeTokenResponses[keyof ProcessUnsubscribeTokenResponses];
