// This file is auto-generated by @hey-api/openapi-ts

export interface QuoteCheckoutData {
  path?: never;
  body: {
    discountCode?: string;
    listingIds: Array<string>;
  };
  query?: never;
  url: '/api/v1/checkout/quote';
}

export interface QuoteCheckoutErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type QuoteCheckoutError = QuoteCheckoutErrors[keyof QuoteCheckoutErrors];

export interface QuoteCheckoutResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      appliedSellerCoupons: Array<{
        id: string;
        sellerId: string;
        allocations: Array<{
          listingId: string;
          /**
           * PKR amount as a number.
           */
          discountAmount: number;
        }>;
        code: string;
        /**
         * PKR amount as a number.
         */
        discountAmount: number;
        discountType: 'FIXED' | 'PERCENTAGE';
        discountValue: number;
        scope: 'ITEM_BASED' | 'SELLER_WIDE';
      }>;
      /**
       * PKR amount as a number.
       */
      commissionAmount: number;
      currency: 'PKR';
      /**
       * PKR amount as a number.
       */
      discountAmount: number;
      items: Array<{
        listingId: string;
        sellerCouponId: string | null;
        sellerId: string;
        /**
         * PKR amount as a number.
         */
        commissionAmount: number;
        commissionRate: number;
        /**
         * PKR amount as a number.
         */
        discountAmount: number;
        /**
         * PKR amount as a number.
         */
        marketplaceDiscountAmount: number;
        /**
         * PKR amount as a number.
         */
        platformFeeAmount: number;
        /**
         * PKR amount as a number.
         */
        price: number;
        /**
         * PKR amount as a number.
         */
        sellerCouponDiscountAmount: number;
        /**
         * PKR amount as a number.
         */
        taxAmount: number;
        title: string;
        /**
         * PKR amount as a number.
         */
        total: number;
      }>;
      /**
       * PKR amount as a number.
       */
      marketplaceDiscountAmount: number;
      marketplaceDiscountCode: string | null;
      /**
       * PKR amount as a number.
       */
      platformFeeAmount: number;
      quoteRevision: string;
      /**
       * PKR amount as a number.
       */
      sellerCouponDiscountAmount: number;
      /**
       * PKR amount as a number.
       */
      subtotal: number;
      /**
       * PKR amount as a number.
       */
      subtotalAfterSellerCoupons: number;
      /**
       * PKR amount as a number.
       */
      taxAmount: number;
      taxRate: number;
      /**
       * PKR amount as a number.
       */
      total: number;
      /**
       * PKR amount as a number.
       */
      totalAfterDiscount: number;
    };
    message: string;
    statusCode: 200;
  };
}

export type QuoteCheckoutResponse = QuoteCheckoutResponses[keyof QuoteCheckoutResponses];
