// This file is auto-generated by @hey-api/openapi-ts

export interface ReceiveWhatsAppWebhookData {
  path?: never;
  body: {
    [key: string]: unknown;
    entry: Array<{
      id: string;
      [key: string]: unknown;
      changes: Array<{
        [key: string]: unknown;
        field: string;
        value: {
          [key: string]: unknown;
          messages?: Array<{
            [key: string]: unknown;
          }>;
          metadata: {
            [key: string]: unknown;
            phone_number_id: string;
          };
        };
      }>;
    }>;
    object: 'whatsapp_business_account';
  };
  headers?: {
    'x-hub-signature-256'?: string;
  };
  query?: never;
  url: '/api/v1/whatsapp/webhook';
}

export interface ReceiveWhatsAppWebhookErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  500: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 500;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ReceiveWhatsAppWebhookError = ReceiveWhatsAppWebhookErrors[keyof ReceiveWhatsAppWebhookErrors];

export interface ReceiveWhatsAppWebhookResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type ReceiveWhatsAppWebhookResponse = ReceiveWhatsAppWebhookResponses[keyof ReceiveWhatsAppWebhookResponses];
