// This file is auto-generated by @hey-api/openapi-ts

export interface RecordAdminPayoutRunItemPaymentData {
  path: {
    itemId: string;
  };
  body: {
    amountMinorUnits: number;
    idempotencyKey: string;
    paidAt?: string;
  };
  query?: never;
  url: '/api/v1/admin/payout-runs/items/{itemId}/status';
}

export interface RecordAdminPayoutRunItemPaymentErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type RecordAdminPayoutRunItemPaymentError = RecordAdminPayoutRunItemPaymentErrors[keyof RecordAdminPayoutRunItemPaymentErrors];

export interface RecordAdminPayoutRunItemPaymentResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      buyerId: string | null;
      complaintId: string | null;
      orderId: string | null;
      orderItemId: string | null;
      payoutRunId: string;
      sellerId: string | null;
      userId: string;
      amount: number;
      bankAccountHolder: string | null;
      bankAccountNumber: string | null;
      bankIban: string | null;
      bankName: string | null;
      bankSwift: string | null;
      itemType: 'BUYER_REFUND' | 'SELLER_PAYOUT';
      payoutComponent: 'BASE' | 'SELLER_INCENTIVE_BONUS';
      periodEnd: string;
      periodStart: string;
      sourceDate: string | null;
      sourceMetadata: unknown;
      sourceStatus: string;
      sourceType: string;
      status: 'PAID' | 'UNPAID';
      userFullName: string;
      paidAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type RecordAdminPayoutRunItemPaymentResponse = RecordAdminPayoutRunItemPaymentResponses[keyof RecordAdminPayoutRunItemPaymentResponses];
