// This file is auto-generated by @hey-api/openapi-ts

export interface ReconnectAdminQuickBooksConnectionData {
  path?: never;
  body: {
    environment: 'PRODUCTION' | 'SANDBOX';
  };
  query?: never;
  url: '/api/v1/admin/quickbooks-connection/reconnect';
}

export interface ReconnectAdminQuickBooksConnectionErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  503: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 503;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ReconnectAdminQuickBooksConnectionError = ReconnectAdminQuickBooksConnectionErrors[keyof ReconnectAdminQuickBooksConnectionErrors];

export interface ReconnectAdminQuickBooksConnectionResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      authorizationUrl: string;
      environment: 'PRODUCTION' | 'SANDBOX';
    };
    message: string;
    statusCode: 200;
  };
}

export type ReconnectAdminQuickBooksConnectionResponse = ReconnectAdminQuickBooksConnectionResponses[keyof ReconnectAdminQuickBooksConnectionResponses];
