// This file is auto-generated by @hey-api/openapi-ts

export interface ResolveAdminReportData {
  path: {
    reportId: string;
  };
  body: {
    adminNotes?: string;
    status: 'DISMISSED' | 'RESOLVED';
  };
  query?: never;
  url: '/api/v1/admin/reports/{reportId}/resolve';
}

export interface ResolveAdminReportErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ResolveAdminReportError = ResolveAdminReportErrors[keyof ResolveAdminReportErrors];

export interface ResolveAdminReportResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      conversationId: string | null;
      listingId: string | null;
      messageId: string | null;
      reportedUserId: string | null;
      reporterId: string;
      adminNotes: string | null;
      details: string | null;
      listingTitle: string | null;
      messageContent: string | null;
      reason: string;
      reportedUserFullName: string | null;
      reporterFullName: string;
      resolverFullName: string | null;
      status: 'DISMISSED' | 'OPEN' | 'RESOLVED';
      resolvedAt: string | null;
      resolvedBy: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type ResolveAdminReportResponse = ResolveAdminReportResponses[keyof ResolveAdminReportResponses];
