// This file is auto-generated by @hey-api/openapi-ts

export interface ResubmitMyManualPaymentOrderData {
  path: {
    orderId: string;
  };
  body: {
    proofFileId: string;
    senderAccountNumber: string;
    senderAccountTitle: string;
  };
  query?: never;
  url: '/api/v1/checkout/orders/{orderId}/resubmit';
}

export interface ResubmitMyManualPaymentOrderErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ResubmitMyManualPaymentOrderError = ResubmitMyManualPaymentOrderErrors[keyof ResubmitMyManualPaymentOrderErrors];

export interface ResubmitMyManualPaymentOrderResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      orderId: string;
      proofFileId: string;
      reviewNote: string | null;
      status: 'APPROVED' | 'REJECTED' | 'RESUBMISSION_REQUESTED' | 'SUBMITTED';
      reviewedAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type ResubmitMyManualPaymentOrderResponse = ResubmitMyManualPaymentOrderResponses[keyof ResubmitMyManualPaymentOrderResponses];
