// This file is auto-generated by @hey-api/openapi-ts

export interface StartConversationData {
  path?: never;
  body: {
    listingId: string;
    content: string;
  };
  query?: never;
  url: '/api/v1/me/conversations';
}

export interface StartConversationErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type StartConversationError = StartConversationErrors[keyof StartConversationErrors];

export interface StartConversationResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      id: string;
      buyerId: string;
      listingId: string | null;
      offerId: string | null;
      sellerId: string;
      amount: number | null;
      buyerFullName: string;
      counterAmount: number | null;
      lastMessageContent: string | null;
      listingStatus: 'APPROVED' | 'NEEDS_REVISION' | 'PENDING' | 'REJECTED' | 'RESERVED' | 'SOLD' | null;
      listingTitle: string;
      offerStatus: 'ACCEPTED' | 'COUNTERED' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'WITHDRAWN' | null;
      reservedUntil: string | null;
      sellerFullName: string;
      unreadCount: number;
      lastMessageCreatedAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type StartConversationResponse = StartConversationResponses[keyof StartConversationResponses];
