// This file is auto-generated by @hey-api/openapi-ts

export interface UnsubscribeMyEmailData {
  path?: never;
  body: {
    reason?: string;
  };
  query?: never;
  url: '/api/v1/preferences/me/unsubscribe';
}

export interface UnsubscribeMyEmailErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UnsubscribeMyEmailError = UnsubscribeMyEmailErrors[keyof UnsubscribeMyEmailErrors];

export interface UnsubscribeMyEmailResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type UnsubscribeMyEmailResponse = UnsubscribeMyEmailResponses[keyof UnsubscribeMyEmailResponses];
