// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateAdminSettingsData {
  path?: never;
  body: {
    boostPackages?: Array<{
      id: string;
      active: boolean;
      credits: number;
      description: string;
      durationDays: number;
      name: string;
      placement: 'FOR_YOU' | 'SEARCH' | 'TRENDING';
      price: number;
    }>;
    emailTemplates?: Array<{
      key: string;
      id: string;
      body: string;
      subject: string;
    }>;
    flagKeywords?: Array<string>;
    helpCategories?: Array<{
      key: string;
      active: boolean;
      blurb: string;
      icon: string;
      label: string;
      sortOrder: number;
    }>;
    helpFaqs?: Array<{
      id: string;
      answer: string;
      categoryKey: string;
      published: boolean;
      question: string;
      sortOrder: number;
    }>;
  };
  query?: never;
  url: '/api/v1/admin/settings';
}

export interface UpdateAdminSettingsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateAdminSettingsError = UpdateAdminSettingsErrors[keyof UpdateAdminSettingsErrors];

export interface UpdateAdminSettingsResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      boostPackages: Array<{
        id: string;
        active: boolean;
        credits: number;
        description: string;
        durationDays: number;
        name: string;
        placement: 'FOR_YOU' | 'SEARCH' | 'TRENDING';
        price: number;
      }>;
      emailTemplates: Array<{
        key: string;
        id: string;
        body: string;
        subject: string;
      }>;
      flagKeywords: Array<string>;
      helpCategories: Array<{
        key: string;
        active: boolean;
        blurb: string;
        icon: string;
        label: string;
        sortOrder: number;
      }>;
      helpFaqs: Array<{
        id: string;
        answer: string;
        categoryKey: string;
        published: boolean;
        question: string;
        sortOrder: number;
      }>;
    };
    message: string;
    statusCode: 200;
  };
}

export type UpdateAdminSettingsResponse = UpdateAdminSettingsResponses[keyof UpdateAdminSettingsResponses];
