// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateAdminCommissionTierData {
  path: {
    resourceId: string;
  };
  body: {
    active?: boolean;
    categories?: Array<string>;
    maxPrice?: number | null;
    minPrice?: number;
    name?: string;
    rate?: number;
    sortOrder?: number;
  };
  query?: never;
  url: '/api/v1/admin/settings/commission-tiers/{resourceId}';
}

export interface UpdateAdminCommissionTierErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateAdminCommissionTierError = UpdateAdminCommissionTierErrors[keyof UpdateAdminCommissionTierErrors];

export interface UpdateAdminCommissionTierResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      active: boolean;
      categories: Array<string>;
      maxPrice: number | null;
      minPrice: number;
      name: string;
      rate: number;
      sortOrder: number;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type UpdateAdminCommissionTierResponse = UpdateAdminCommissionTierResponses[keyof UpdateAdminCommissionTierResponses];
