// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateAdminUserRoleData {
  path: {
    userId: string;
  };
  body: {
    roleId: string;
  };
  query?: never;
  url: '/api/v1/admin/users/{userId}/role';
}

export interface UpdateAdminUserRoleErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateAdminUserRoleError = UpdateAdminUserRoleErrors[keyof UpdateAdminUserRoleErrors];

export interface UpdateAdminUserRoleResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      roleId: string | null;
      address: string;
      email: string;
      firstName: string;
      image: unknown;
      lastName: string;
      marketingEmailConsent: boolean;
      phone: string;
      roleName: string | null;
      /**
       * User status.
       */
      status: 'ACTIVE' | 'INACTIVE';
      termsVersion: string | null;
      username: string;
      marketingEmailConsentUpdatedAt: string | null;
      termsAcceptedAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type UpdateAdminUserRoleResponse = UpdateAdminUserRoleResponses[keyof UpdateAdminUserRoleResponses];
