// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateMarketingEmailConsentData {
  path?: never;
  body: {
    marketingEmailConsent: boolean;
  };
  query?: never;
  url: '/api/v1/auth/marketing-consent';
}

export interface UpdateMarketingEmailConsentErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateMarketingEmailConsentError = UpdateMarketingEmailConsentErrors[keyof UpdateMarketingEmailConsentErrors];

export interface UpdateMarketingEmailConsentResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type UpdateMarketingEmailConsentResponse = UpdateMarketingEmailConsentResponses[keyof UpdateMarketingEmailConsentResponses];
