// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateAdminSiteSettingData {
  path: {
    key: string;
  };
  body: {
    value: {
      addressBody?: string;
      addressLabel?: string;
      emailAddress?: string;
      emailLabel?: string;
      mapUrl?: string;
      officeHours?: string;
      phoneLabel?: string;
      phoneNumber?: string;
    } | {
      alt?: string;
      badgeIconUrl?: string;
      badgeText?: string;
      headlineLine1?: string;
      headlineLine1Color?: string;
      headlineLine2?: string;
      headlineLine2Color?: string;
      mobileUrl?: string;
      primaryCtaBg?: string;
      primaryCtaLabel?: string;
      primaryCtaTextColor?: string;
      secondaryCtaBorderColor?: string;
      secondaryCtaLabel?: string;
      secondaryCtaTextColor?: string;
      siteLogoUrl?: string;
      subtitle?: string;
      subtitleColor?: string;
      url?: string;
    } | {
      ctaLabel?: string;
      ctaUrl?: string;
      eyebrow?: string;
      subtitle?: string;
      title?: string;
    };
  };
  query?: never;
  url: '/api/v1/admin/settings/site-settings/{key}';
}

export interface UpdateAdminSiteSettingErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateAdminSiteSettingError = UpdateAdminSiteSettingErrors[keyof UpdateAdminSiteSettingErrors];

export interface UpdateAdminSiteSettingResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      key: string;
      value: {
        addressBody: string;
        addressLabel: string;
        emailAddress: string;
        emailLabel: string;
        mapUrl: string;
        officeHours: string;
        phoneLabel: string;
        phoneNumber: string;
      } | {
        alt: string;
        badgeIconUrl: string;
        badgeText: string;
        headlineLine1: string;
        headlineLine1Color: string;
        headlineLine2: string;
        headlineLine2Color: string;
        mobileUrl: string;
        primaryCtaBg: string;
        primaryCtaLabel: string;
        primaryCtaTextColor: string;
        secondaryCtaBorderColor: string;
        secondaryCtaLabel: string;
        secondaryCtaTextColor: string;
        siteLogoUrl: string;
        subtitle: string;
        subtitleColor: string;
        url: string;
      } | {
        ctaLabel: string;
        ctaUrl: string;
        eyebrow: string;
        subtitle: string;
        title: string;
      };
    };
    message: string;
    statusCode: 200;
  };
}

export type UpdateAdminSiteSettingResponse = UpdateAdminSiteSettingResponses[keyof UpdateAdminSiteSettingResponses];
