// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateAdminTaxSettingData {
  path: {
    resourceId: string;
  };
  body: {
    active?: boolean;
    name?: string;
    rate?: number;
  };
  query?: never;
  url: '/api/v1/admin/settings/tax-settings/{resourceId}';
}

export interface UpdateAdminTaxSettingErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateAdminTaxSettingError = UpdateAdminTaxSettingErrors[keyof UpdateAdminTaxSettingErrors];

export interface UpdateAdminTaxSettingResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      active: boolean;
      name: string;
      rate: number;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type UpdateAdminTaxSettingResponse = UpdateAdminTaxSettingResponses[keyof UpdateAdminTaxSettingResponses];
