// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateAdminRolePermissionsData {
  path: {
    roleId: string;
  };
  body: {
    /**
     * Array of permission names to assign to the role
     */
    permissions: Array<'ANALYTICS_CREATE' | 'ANALYTICS_DELETE' | 'ANALYTICS_READ' | 'ANALYTICS_UPDATE' | 'BOOSTS_CREATE' | 'BOOSTS_DELETE' | 'BOOSTS_READ' | 'BOOSTS_UPDATE' | 'BRANDS_CREATE' | 'BRANDS_DELETE' | 'BRANDS_READ' | 'BRANDS_UPDATE' | 'CATALOG_CREATE' | 'CATALOG_DELETE' | 'CATALOG_READ' | 'CATALOG_UPDATE' | 'COMPLAINTS_CREATE' | 'COMPLAINTS_DELETE' | 'COMPLAINTS_READ' | 'COMPLAINTS_UPDATE' | 'FINANCE_ADJUSTMENTS_CREATE' | 'FINANCE_ADJUSTMENTS_READ' | 'FINANCE_ADJUSTMENTS_REVIEW' | 'FINANCE_DASHBOARD_CREATE' | 'FINANCE_DASHBOARD_DELETE' | 'FINANCE_DASHBOARD_READ' | 'FINANCE_DASHBOARD_UPDATE' | 'FINANCE_QUICKBOOKS_CONNECTION_MANAGE' | 'FINANCE_QUICKBOOKS_CONNECTION_READ' | 'FINANCE_QUICKBOOKS_MAPPINGS_MANAGE' | 'FINANCE_QUICKBOOKS_MAPPINGS_READ' | 'FINANCE_QUICKBOOKS_SYNC_MANAGE' | 'FINANCE_QUICKBOOKS_SYNC_READ' | 'FINANCE_REPORTS_CREATE' | 'FINANCE_REPORTS_DELETE' | 'FINANCE_REPORTS_READ' | 'FINANCE_REPORTS_UPDATE' | 'LISTINGS_CREATE' | 'LISTINGS_DELETE' | 'LISTINGS_READ' | 'LISTINGS_UPDATE' | 'MARKETING_LEADS_CREATE' | 'MARKETING_LEADS_DELETE' | 'MARKETING_LEADS_READ' | 'MARKETING_LEADS_UPDATE' | 'MESSAGES_CREATE' | 'MESSAGES_DELETE' | 'MESSAGES_READ' | 'MESSAGES_UPDATE' | 'ORDERS_CREATE' | 'ORDERS_DELETE' | 'ORDERS_READ' | 'ORDERS_UPDATE' | 'PAYOUTS_CREATE' | 'PAYOUTS_DELETE' | 'PAYOUTS_READ' | 'PAYOUTS_UPDATE' | 'REPORTS_CREATE' | 'REPORTS_DELETE' | 'REPORTS_READ' | 'REPORTS_UPDATE' | 'RETURNS_CREATE' | 'RETURNS_DELETE' | 'RETURNS_READ' | 'RETURNS_UPDATE' | 'SELLER_COUPONS_CREATE' | 'SELLER_COUPONS_DELETE' | 'SELLER_COUPONS_READ' | 'SELLER_COUPONS_UPDATE' | 'SETTINGS_CREATE' | 'SETTINGS_DELETE' | 'SETTINGS_READ' | 'SETTINGS_UPDATE' | 'SUPPORT_TICKETS_CREATE' | 'SUPPORT_TICKETS_DELETE' | 'SUPPORT_TICKETS_READ' | 'SUPPORT_TICKETS_UPDATE'>;
  };
  query?: never;
  url: '/api/v1/admin/roles/{roleId}/permissions';
}

export interface UpdateAdminRolePermissionsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateAdminRolePermissionsError = UpdateAdminRolePermissionsErrors[keyof UpdateAdminRolePermissionsErrors];

export interface UpdateAdminRolePermissionsResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      name: string;
      permissions: Array<{
        id: string;
        name: string;
        createdAt: string;
        updatedAt: string;
      }>;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type UpdateAdminRolePermissionsResponse = UpdateAdminRolePermissionsResponses[keyof UpdateAdminRolePermissionsResponses];
