// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateMyBankDetailsData {
  path?: never;
  body: {
    bankAccountHolder?: string;
    bankAccountNumber?: string;
    bankIban?: string;
    bankName?: string;
    bankSwift?: string;
  };
  query?: never;
  url: '/api/v1/profiles/me/bank-details';
}

export interface UpdateMyBankDetailsErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateMyBankDetailsError = UpdateMyBankDetailsErrors[keyof UpdateMyBankDetailsErrors];

export interface UpdateMyBankDetailsResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      userId: string;
      address: string;
      bankAccountHolder: string;
      bankAccountNumber: string;
      bankIban: string;
      bankName: string;
      bankSwift: string;
      bio: string;
      dateOfBirth: string;
      fullName: string;
      image: {
        /**
         * Unique identifier of the uploaded file.
         */
        id: string;
        /**
         * Original filename of the uploaded image.
         */
        filename: string;
        /**
         * MIME type of the uploaded image.
         */
        mimetype: string;
        size: number | string;
        /**
         * Publicly accessible URL of the uploaded image.
         */
        url: string;
      } | null;
      location: string;
      phone: string;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type UpdateMyBankDetailsResponse = UpdateMyBankDetailsResponses[keyof UpdateMyBankDetailsResponses];
