// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateAdminFlaggedBuyerRulesData {
  path?: never;
  body: {
    threshold?: number;
    windowDays?: number;
  };
  query?: never;
  url: '/api/v1/admin/flagged-buyers/rules';
}

export interface UpdateAdminFlaggedBuyerRulesErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateAdminFlaggedBuyerRulesError = UpdateAdminFlaggedBuyerRulesErrors[keyof UpdateAdminFlaggedBuyerRulesErrors];

export interface UpdateAdminFlaggedBuyerRulesResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      threshold: number;
      windowDays: number;
    };
    message: string;
    statusCode: 200;
  };
}

export type UpdateAdminFlaggedBuyerRulesResponse = UpdateAdminFlaggedBuyerRulesResponses[keyof UpdateAdminFlaggedBuyerRulesResponses];
