// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateAdminSellerCouponData {
  path: {
    id: string;
  };
  body: {
    listingId?: string | null;
    sellerId?: string;
    active?: boolean;
    code?: string;
    discountType?: 'FIXED' | 'PERCENTAGE';
    discountValue?: number;
    maxOrders?: number | null;
    minOrderAmount?: number;
    scope?: 'ITEM_BASED' | 'SELLER_WIDE';
    expiresAt?: string | null;
    startsAt?: string | null;
  };
  query?: never;
  url: '/api/v1/admin/seller-coupons/{id}';
}

export interface UpdateAdminSellerCouponErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateAdminSellerCouponError = UpdateAdminSellerCouponErrors[keyof UpdateAdminSellerCouponErrors];

export interface UpdateAdminSellerCouponResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      listingId: string | null;
      sellerId: string;
      active: boolean;
      code: string;
      currentOrders: number;
      discountType: 'FIXED' | 'PERCENTAGE';
      discountValue: number;
      maxOrders: number | null;
      minOrderAmount: number;
      reservedOrders: number;
      scope: 'ITEM_BASED' | 'SELLER_WIDE';
      expiresAt: string | null;
      startsAt: string | null;
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type UpdateAdminSellerCouponResponse = UpdateAdminSellerCouponResponses[keyof UpdateAdminSellerCouponResponses];
