// This file is auto-generated by @hey-api/openapi-ts

export interface UpdateOrderItemStatusData {
  path: {
    orderId: string;
    orderItemId: string;
  };
  body: {
    expectedDelivery: string;
    shippingMethod: string;
    status: 'SHIPPED';
    trackingNumber: string;
  } | {
    status: 'DELIVERED';
  };
  query?: never;
  url: '/api/v1/orders/{orderId}/items/{orderItemId}/status';
}

export interface UpdateOrderItemStatusErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UpdateOrderItemStatusError = UpdateOrderItemStatusErrors[keyof UpdateOrderItemStatusErrors];

export interface UpdateOrderItemStatusResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type UpdateOrderItemStatusResponse = UpdateOrderItemStatusResponses[keyof UpdateOrderItemStatusResponses];
