// This file is auto-generated by @hey-api/openapi-ts

export interface UploadOrderItemShippingProofData {
  path: {
    orderId: string;
    orderItemId: string;
  };
  body: {
    proofImageUrl: string;
  };
  query?: never;
  url: '/api/v1/orders/{orderId}/items/{orderItemId}/shipping-proof';
}

export interface UploadOrderItemShippingProofErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UploadOrderItemShippingProofError = UploadOrderItemShippingProofErrors[keyof UploadOrderItemShippingProofErrors];

export interface UploadOrderItemShippingProofResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type UploadOrderItemShippingProofResponse = UploadOrderItemShippingProofResponses[keyof UploadOrderItemShippingProofResponses];
