// This file is auto-generated by @hey-api/openapi-ts

export interface UploadFileData {
  path?: never;
  body: {
    file: Blob | File;
    purpose?: 'PAYMENT_PROOF';
  };
  query?: never;
  url: '/api/upload-file';
}

export interface UploadFileErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export interface UploadFileResponses {
  /**
   * Default Response
   */
  201: {
    data: {
      /**
       * Unique identifier of the uploaded file.
       */
      id: string;
      /**
       * Original filename of the uploaded file.
       */
      filename: string;
      /**
       * MIME type of the uploaded file.
       */
      mimetype: string;
      size: number | string;
      /**
       * Publicly accessible URL of the uploaded file.
       */
      url: string;
    } | {
      id: string;
    };
    message: string;
    statusCode: 201;
  };
}

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];
