// This file is auto-generated by @hey-api/openapi-ts

export interface ValidateCheckoutDiscountData {
  path?: never;
  body: {
    code: string;
    listingIds: Array<string>;
  };
  query?: never;
  url: '/api/v1/checkout/validate-discount';
}

export interface ValidateCheckoutDiscountErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ValidateCheckoutDiscountError = ValidateCheckoutDiscountErrors[keyof ValidateCheckoutDiscountErrors];

export interface ValidateCheckoutDiscountResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      code: string;
      /**
       * PKR amount as a number.
       */
      commissionAmount: number;
      currency: 'PKR';
      /**
       * PKR amount as a number.
       */
      discountAmount: number;
      discountType: 'FIXED' | 'PERCENTAGE';
      discountValue: number;
      /**
       * PKR amount as a number.
       */
      platformFeeAmount: number;
      /**
       * PKR amount as a number.
       */
      subtotal: number;
      /**
       * PKR amount as a number.
       */
      taxAmount: number;
      taxRate: number;
      /**
       * PKR amount as a number.
       */
      total: number;
      /**
       * PKR amount as a number.
       */
      totalAfterDiscount: number;
    };
    message: string;
    statusCode: 200;
  };
}

export type ValidateCheckoutDiscountResponse = ValidateCheckoutDiscountResponses[keyof ValidateCheckoutDiscountResponses];
