// This file is auto-generated by @hey-api/openapi-ts

export interface ValidateCheckoutSellerCouponData {
  path?: never;
  body: {
    code: string;
    listingIds: Array<string>;
  };
  query?: never;
  url: '/api/v1/checkout/validate-seller-coupon';
}

export interface ValidateCheckoutSellerCouponErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ValidateCheckoutSellerCouponError = ValidateCheckoutSellerCouponErrors[keyof ValidateCheckoutSellerCouponErrors];

export interface ValidateCheckoutSellerCouponResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      sellerId: string;
      code: string;
      currency: 'PKR';
      /**
       * PKR amount as a number.
       */
      discountAmount: number;
      discountType: 'FIXED' | 'PERCENTAGE';
      discountValue: number;
      /**
       * PKR amount as a number.
       */
      eligibleSubtotal: number;
    };
    message: string;
    statusCode: 200;
  };
}

export type ValidateCheckoutSellerCouponResponse = ValidateCheckoutSellerCouponResponses[keyof ValidateCheckoutSellerCouponResponses];
