// This file is auto-generated by @hey-api/openapi-ts

export interface ValidateUnsubscribeTokenData {
  path?: never;
  body?: never;
  query: {
    token: string;
  };
  url: '/api/v1/emails/unsubscribe';
}

export interface ValidateUnsubscribeTokenErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type ValidateUnsubscribeTokenError = ValidateUnsubscribeTokenErrors[keyof ValidateUnsubscribeTokenErrors];

export interface ValidateUnsubscribeTokenResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      reason?: string;
      valid: boolean;
    };
    message: string;
    statusCode: 200;
  };
}

export type ValidateUnsubscribeTokenResponse = ValidateUnsubscribeTokenResponses[keyof ValidateUnsubscribeTokenResponses];
