// This file is auto-generated by @hey-api/openapi-ts

export interface VerifyUserEmailData {
  path?: never;
  body: {
    email: string;
    otp: string;
  };
  query?: never;
  url: '/api/v1/auth/verify-email';
}

export interface VerifyUserEmailErrors {
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type VerifyUserEmailError = VerifyUserEmailErrors[keyof VerifyUserEmailErrors];

export interface VerifyUserEmailResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type VerifyUserEmailResponse = VerifyUserEmailResponses[keyof VerifyUserEmailResponses];
