// This file is auto-generated by @hey-api/openapi-ts

export interface WarnAdminFlaggedBuyerData {
  path: {
    buyerId: string;
  };
  body: {
    message?: string;
  };
  query?: never;
  url: '/api/v1/admin/flagged-buyers/{buyerId}/warn';
}

export interface WarnAdminFlaggedBuyerErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  403: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 403;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type WarnAdminFlaggedBuyerError = WarnAdminFlaggedBuyerErrors[keyof WarnAdminFlaggedBuyerErrors];

export interface WarnAdminFlaggedBuyerResponses {
  /**
   * Default Response
   */
  200: {
    message: string;
    statusCode: 200;
  };
}

export type WarnAdminFlaggedBuyerResponse = WarnAdminFlaggedBuyerResponses[keyof WarnAdminFlaggedBuyerResponses];
