// This file is auto-generated by @hey-api/openapi-ts

export interface WithdrawOfferData {
  path: {
    offerId: string;
  };
  body?: never;
  query?: never;
  url: '/api/v1/me/offers/{offerId}/withdraw';
}

export interface WithdrawOfferErrors {
  /**
   * Default Response
   */
  400: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 400;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  401: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 401;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  404: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 404;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
  /**
   * Default Response
   */
  409: {
    /**
     * Request identifier for tracing the error
     */
    requestId: string;
    /**
     * Http status code of the error response
     */
    statusCode: 409;
    /**
     * Detailed human-readable error message
     */
    message: string;
    /**
     * Application or framework-specific error code
     */
    code: string;
    /**
     * Field-level validation errors when applicable
     */
    fieldErrors?: Array<{
      field: string;
      message: string;
    }>;
  };
}

export type WithdrawOfferError = WithdrawOfferErrors[keyof WithdrawOfferErrors];

export interface WithdrawOfferResponses {
  /**
   * Default Response
   */
  200: {
    data: {
      id: string;
      buyerId: string;
      conversationId: string | null;
      listingId: string;
      sellerId: string;
      amount: number;
      buyerFullName: string;
      counterAmount: number | null;
      coverImage: {
        /**
         * Unique identifier of the uploaded file.
         */
        id: string;
        /**
         * Original filename of the uploaded file.
         */
        filename: string;
        /**
         * MIME type of the uploaded file.
         */
        mimetype: string;
        size: number | string;
        /**
         * Publicly accessible URL of the uploaded file.
         */
        url: string;
      } | null;
      listingPrice: number;
      listingStatus: 'APPROVED' | 'NEEDS_REVISION' | 'PENDING' | 'REJECTED' | 'RESERVED' | 'SOLD';
      listingTitle: string;
      message: string | null;
      reservedUntil: string | null;
      sellerFullName: string;
      status: 'ACCEPTED' | 'COUNTERED' | 'EXPIRED' | 'PENDING' | 'REJECTED' | 'WITHDRAWN';
      createdAt: string;
      updatedAt: string;
    };
    message: string;
    statusCode: 200;
  };
}

export type WithdrawOfferResponse = WithdrawOfferResponses[keyof WithdrawOfferResponses];
